/*
 Highcharts 4.0.3 JS v/Highstock 2.0.3 (2014-07-03)

 (c) 2009-2014 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(){function y(a,b){var c;a||(a={});for(c in b)a[c]=b[c];return a}function D(){var a,b=arguments,c,d={},e=function(a,b){var c,d;"object"!==typeof a&&(a={});for(d in b)b.hasOwnProperty(d)&&((c=b[d])&&"object"===typeof c&&"[object Array]"!==Object.prototype.toString.call(c)&&"renderTo"!==d&&"number"!==typeof c.nodeType?a[d]=e(a[d]||{},c):a[d]=b[d]);return a};!0===b[0]&&(d=b[1],b=Array.prototype.slice.call(b,2));c=b.length;for(a=0;a<c;a++)d=e(d,b[a]);return d}function B(a,b){return parseInt(a,
b||10)}function ea(a){return"string"===typeof a}function Z(a){return a&&"object"===typeof a}function ma(a){return"[object Array]"===Object.prototype.toString.call(a)}function $(a){return"number"===typeof a}function Ia(a){return J.log(a)/J.LN10}function aa(a){return J.pow(10,a)}function na(a,b){for(var c=a.length;c--;)if(a[c]===b){a.splice(c,1);break}}function u(a){return a!==w&&null!==a}function C(a,b,c){var d,e;if(ea(b))u(c)?a.setAttribute(b,c):a&&a.getAttribute&&(e=a.getAttribute(b));else if(u(b)&&
Z(b))for(d in b)a.setAttribute(d,b[d]);return e}function oa(a){return ma(a)?a:[a]}function r(){var a=arguments,b,c,d=a.length;for(b=0;b<d;b++)if(c=a[b],c!==w&&null!==c)return c}function N(a,b){fa&&!O&&b&&b.opacity!==w&&(b.filter="alpha(opacity="+100*b.opacity+")");y(a.style,b)}function pa(a,b,c,d,e){a=A.createElement(a);b&&y(a,b);e&&N(a,{padding:0,border:P,margin:0});c&&N(a,c);d&&d.appendChild(a);return a}function Ua(a,b){var c=function(){return w};c.prototype=new a;y(c.prototype,b);return c}function ga(a,
b,c,d){var e=I.lang;a=+a||0;var f=-1===b?(a.toString().split(".")[1]||"").length:isNaN(b=W(b))?2:b;b=void 0===c?e.decimalPoint:c;d=void 0===d?e.thousandsSep:d;e=0>a?"-":"";c=String(B(a=W(a).toFixed(f)));var g=3<c.length?c.length%3:0;return e+(g?c.substr(0,g)+d:"")+c.substr(g).replace(/(\d{3})(?=\d)/g,"$1"+d)+(f?b+W(a-c).toFixed(f).slice(2):"")}function ha(a,b){return Array((b||2)+1-String(a).length).join(0)+a}function Ja(a,b,c){var d=a[b];a[b]=function(){var a=Array.prototype.slice.call(arguments);
a.unshift(d);return c.apply(this,a)}}function va(a,b){for(var c="{",d=!1,e,f,g,h,k,l=[];-1!==(c=a.indexOf(c));){e=a.slice(0,c);if(d){f=e.split(":");g=f.shift().split(".");k=g.length;e=b;for(h=0;h<k;h++)e=e[g[h]];f.length&&(f=f.join(":"),g=/\.([0-9])/,h=I.lang,k=void 0,/f$/.test(f)?(k=(k=f.match(g))?k[1]:-1,null!==e&&(e=ga(e,k,h.decimalPoint,-1<f.indexOf(",")?h.thousandsSep:""))):e=wa(f,e))}l.push(e);a=a.slice(c+1);c=(d=!d)?"}":"{"}l.push(a);return l.join("")}function mb(a,b,c,d){var e;c=r(c,1);e=
a/c;b||(b=[1,2,2.5,5,10],d&&!1===d.allowDecimals&&(1===c?b=[1,2,5,10]:.1>=c&&(b=[1/c])));for(d=0;d<b.length&&!(a=b[d],e<=(b[d]+(b[d+1]||b[d]))/2);d++);return a*c}function Ka(a,b){var c=a.length,d,e;for(e=0;e<c;e++)a[e].ss_i=e;a.sort(function(a,c){d=b(a,c);return 0===d?a.ss_i-c.ss_i:d});for(e=0;e<c;e++)delete a[e].ss_i}function xa(a){for(var b=a.length,c=a[0];b--;)a[b]<c&&(c=a[b]);return c}function qa(a){for(var b=a.length,c=a[0];b--;)a[b]>c&&(c=a[b]);return c}function ya(a,b){for(var c in a)a[c]&&
a[c]!==b&&a[c].destroy&&a[c].destroy(),delete a[c]}function za(a){Aa||(Aa=pa(Va));a&&Aa.appendChild(a);Aa.innerHTML=""}function X(a){return parseFloat(a.toPrecision(14))}function Wa(){var a=I.global.useUTC,b=a?"getUTC":"get";Xa=6E4*(a&&I.global.timezoneOffset||0);Ya=b+"Minutes";Za=b+"Hours";$a=b+"Day";ab=b+"Date";bb=b+"Month";cb=b+"FullYear"}function K(){}function ja(a,b,c,d){this.axis=a;this.pos=b;this.type=c||"";this.isNew=!0;c||d||this.addLabel()}function Ba(){this.init.apply(this,arguments)}function La(){this.init.apply(this,
arguments)}var w,A=document,x=window,J=Math,z=J.round,Q=J.floor,ka=J.ceil,v=J.max,U=J.min,W=J.abs,ra=J.cos,Ca=J.sin,db=J.PI,eb=2*db/360,ia=navigator.userAgent,nb=x.opera,fa=/msie/i.test(ia)&&!nb,ob=/AppleWebKit/.test(ia),Da=/Firefox/.test(ia),fb=/(Mobile|Android|Windows Phone)/.test(ia),O=!!A.createElementNS&&!!A.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect,pb=Da&&4>parseInt(ia.split("Firefox/")[1],10),Y=!O&&!fa&&!!A.createElement("canvas").getContext,gb={},Ma=0,Aa,I,wa,R,Na,
S,ba=[],hb=0,Va="div",P="none",qb=/^[0-9]+$/,Xa,Ya,Za,$a,ab,bb,cb,sa={},ca;x.Highcharts?S(16,!0):ca=x.Highcharts={};wa=function(a,b,c){if(!u(b)||isNaN(b))return"Invalid date";a=r(a,"%Y-%m-%d %H:%M:%S");var d=new Date(b-Xa),e,f=d[Za](),g=d[$a](),h=d[ab](),k=d[bb](),l=d[cb](),m=I.lang,p=m.weekdays,d=y({a:p[g].substr(0,3),A:p[g],d:ha(h),e:h,b:m.shortMonths[k],B:m.months[k],m:ha(k+1),y:l.toString().substr(2,2),Y:l,H:ha(f),I:ha(f%12||12),l:f%12||12,M:ha(d[Ya]()),p:12>f?"AM":"PM",P:12>f?"am":"pm",S:ha(d.getSeconds()),
L:ha(z(b%1E3),3)},ca.dateFormats);for(e in d)for(;-1!==a.indexOf("%"+e);)a=a.replace("%"+e,"function"===typeof d[e]?d[e](b):d[e]);return c?a.substr(0,1).toUpperCase()+a.substr(1):a};S=function(a,b){var c="Highcharts error #"+a+": www.highcharts.com/errors/"+a;if(b)throw c;x.console&&console.log(c)};Na={init:function(a,b,c){b=b||"";var d=a.shift,e=-1<b.indexOf("C"),f=e?7:3,g;b=b.split(" ");c=[].concat(c);var h,k,l=function(a){for(g=a.length;g--;)"M"===a[g]&&a.splice(g+1,0,a[g+1],a[g+2],a[g+1],a[g+
2])};e&&(l(b),l(c));a.isArea&&(h=b.splice(b.length-6,6),k=c.splice(c.length-6,6));if(d<=c.length/f&&b.length===c.length)for(;d--;)c=[].concat(c).splice(0,f).concat(c);a.shift=0;if(b.length)for(a=c.length;b.length<a;)d=[].concat(b).splice(b.length-f,f),e&&(d[f-6]=d[f-2],d[f-5]=d[f-1]),b=b.concat(d);h&&(b=b.concat(h),c=c.concat(k));return[b,c]},step:function(a,b,c,d){var e=[],f=a.length;if(1===c)e=d;else if(f===b.length&&1>c)for(;f--;)d=parseFloat(a[f]),e[f]=isNaN(d)?a[f]:c*parseFloat(b[f]-d)+d;else e=
b;return e}};(function(a){x.HighchartsAdapter=x.HighchartsAdapter||a&&{init:function(b){var c=a.fx,d=c.step,e,f=a.Tween,g=f&&f.propHooks;e=a.cssHooks.opacity;a.extend(a.easing,{easeOutQuad:function(a,b,c,d,e){return-d*(b/=e)*(b-2)+c}});a.each(["cur","_default","width","height","opacity"],function(a,b){var e=d,m;"cur"===b?e=c.prototype:"_default"===b&&f&&(e=g[b],b="set");(m=e[b])&&(e[b]=function(c){var d;c=a?c:this;if("align"!==c.prop)return d=c.elem,d.attr?d.attr(c.prop,"cur"===b?w:c.now):m.apply(this,
arguments)})});Ja(e,"get",function(a,b,c){return b.attr?b.opacity||0:a.call(this,b,c)});e=function(a){var c=a.elem,d;a.started||(d=b.init(c,c.d,c.toD),a.start=d[0],a.end=d[1],a.started=!0);c.attr("d",b.step(a.start,a.end,a.pos,c.toD))};f?g.d={set:e}:d.d=e;this.each=Array.prototype.forEach?function(a,b){return Array.prototype.forEach.call(a,b)}:function(a,b){var c,d=a.length;for(c=0;c<d;c++)if(!1===b.call(a[c],a[c],c,a))return c};a.fn.highcharts=function(){var a="Chart",b=arguments,c,d;this[0]&&(ea(b[0])&&
(a=b[0],b=Array.prototype.slice.call(b,1)),c=b[0],c!==w&&(c.chart=c.chart||{},c.chart.renderTo=this[0],new ca[a](c,b[1]),d=this),c===w&&(d=ba[C(this[0],"data-highcharts-chart")]));return d}},getScript:a.getScript,inArray:a.inArray,adapterRun:function(b,c){return a(b)[c]()},grep:a.grep,map:function(a,c){for(var d=[],e=0,f=a.length;e<f;e++)d[e]=c.call(a[e],a[e],e,a);return d},offset:function(b){return a(b).offset()},addEvent:function(b,c,d){a(b).bind(c,d)},removeEvent:function(b,c,d){var e=A.removeEventListener?
"removeEventListener":"detachEvent";A[e]&&b&&!b[e]&&(b[e]=function(){});a(b).unbind(c,d)},fireEvent:function(b,c,d,e){var f=a.Event(c),g="detached"+c,h;!fa&&d&&(delete d.layerX,delete d.layerY,delete d.returnValue);y(f,d);b[c]&&(b[g]=b[c],b[c]=null);a.each(["preventDefault","stopPropagation"],function(a,b){var c=f[b];f[b]=function(){try{c.call(f)}catch(a){"preventDefault"===b&&(h=!0)}}});a(b).trigger(f);b[g]&&(b[c]=b[g],b[g]=null);!e||f.isDefaultPrevented()||h||e(f)},washMouseEvent:function(a){var c=
a.originalEvent||a;c.pageX===w&&(c.pageX=a.pageX,c.pageY=a.pageY);return c},animate:function(b,c,d){var e=a(b);b.style||(b.style={});c.d&&(b.toD=c.d,c.d=1);e.stop();c.opacity!==w&&b.attr&&(c.opacity+="px");e.animate(c,d)},stop:function(b){a(b).stop()}}})(x.jQuery);var Ea=x.HighchartsAdapter,V=Ea||{};Ea&&Ea.init.call(Ea,Na);var Fa=V.adapterRun,rb=V.inArray,s=V.each,ib=V.grep,jb=V.map,L=V.addEvent,T=V.removeEvent,M=V.fireEvent,kb=V.animate,Oa=V.stop,Pa={enabled:!0,x:0,y:15,style:{color:"#606060",cursor:"default",
fontSize:"11px"}};I={colors:"#7cb5ec #434348 #90ed7d #f7a35c #8085e9 #f15c80 #e4d354 #8085e8 #8d4653 #91e8e1".split(" "),symbols:["circle","diamond","square","triangle","triangle-down"],lang:{loading:"Loading...",months:"January February March April May June July August September October November December".split(" "),shortMonths:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),weekdays:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),decimalPoint:".",numericSymbols:"kMGTPE".split(""),
resetZoom:"Reset zoom",resetZoomTitle:"Reset zoom level 1:1",thousandsSep:","},global:{useUTC:!0,canvasToolsURL:"http://code.highcharts.com@product.cdnpath@//Highstock 2.0.3/modules/canvas-tools.js",VMLRadialGradientURL:"http://code.highcharts.com@product.cdnpath@//Highstock 2.0.3/gfx/vml-radial-gradient.png"},chart:{borderColor:"#4572A7",borderRadius:0,defaultSeriesType:"line",ignoreHiddenSeries:!0,spacing:[10,10,15,10],backgroundColor:"#FFFFFF",plotBorderColor:"#C0C0C0",resetZoomButton:{theme:{zIndex:20},
position:{align:"right",x:-10,y:10}}},title:{text:"Chart title",align:"center",margin:15,style:{color:"#333333",fontSize:"18px"}},subtitle:{text:"",align:"center",style:{color:"#555555"}},plotOptions:{line:{allowPointSelect:!1,showCheckbox:!1,animation:{duration:1E3},events:{},lineWidth:2,marker:{lineWidth:0,radius:4,lineColor:"#FFFFFF",states:{hover:{enabled:!0,lineWidthPlus:1,radiusPlus:2},select:{fillColor:"#FFFFFF",lineColor:"#000000",lineWidth:2}}},point:{events:{}},dataLabels:D(Pa,{align:"center",
enabled:!1,formatter:function(){return null===this.y?"":ga(this.y,-1)},verticalAlign:"bottom",y:0}),cropThreshold:300,pointRange:0,states:{hover:{lineWidthPlus:1,marker:{},halo:{size:10,opacity:.25}},select:{marker:{}}},stickyTracking:!0,turboThreshold:1E3}},labels:{style:{position:"absolute",color:"#3E576F"}},legend:{enabled:!0,align:"center",layout:"horizontal",labelFormatter:function(){return this.name},borderColor:"#909090",borderRadius:0,navigation:{activeColor:"#274b6d",inactiveColor:"#CCC"},
shadow:!1,itemStyle:{color:"#333333",fontSize:"12px",fontWeight:"bold"},itemHoverStyle:{color:"#000"},itemHiddenStyle:{color:"#CCC"},itemCheckboxStyle:{position:"absolute",width:"13px",height:"13px"},symbolPadding:5,verticalAlign:"bottom",x:0,y:0,title:{style:{fontWeight:"bold"}}},loading:{labelStyle:{fontWeight:"bold",position:"relative",top:"45%"},style:{position:"absolute",backgroundColor:"white",opacity:.5,textAlign:"center"}},tooltip:{enabled:!0,animation:O,backgroundColor:"rgba(249, 249, 249, .85)",
borderWidth:1,borderRadius:3,dateTimeLabelFormats:{millisecond:"%A, %b %e, %H:%M:%S.%L",second:"%A, %b %e, %H:%M:%S",minute:"%A, %b %e, %H:%M",hour:"%A, %b %e, %H:%M",day:"%A, %b %e, %Y",week:"Week from %A, %b %e, %Y",month:"%B %Y",year:"%Y"},headerFormat:'<span style="font-size: 10px">{point.key}</span><br/>',pointFormat:'<span style="color:{series.color}">\u25cf</span> {series.name}: <b>{point.y}</b><br/>',shadow:!0,snap:fb?25:10,style:{color:"#333333",cursor:"default",fontSize:"12px",padding:"8px",
whiteSpace:"nowrap"}},credits:{enabled:!0,text:"Highcharts.com",href:"http://www.highcharts.com",position:{align:"right",x:-10,verticalAlign:"bottom",y:-5},style:{cursor:"pointer",color:"#909090",fontSize:"9px"}}};var Qa=I.plotOptions;Wa();var sb=/rgba\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]?(?:\.[0-9]+)?)\s*\)/,tb=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/,ub=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/,ta=function(a){var b=[],c,d;(function(a){a&&
a.stops?d=jb(a.stops,function(a){return ta(a[1])}):(c=sb.exec(a))?b=[B(c[1]),B(c[2]),B(c[3]),parseFloat(c[4],10)]:(c=tb.exec(a))?b=[B(c[1],16),B(c[2],16),B(c[3],16),1]:(c=ub.exec(a))&&(b=[B(c[1]),B(c[2]),B(c[3]),1])})(a);return{get:function(c){var f;d?(f=D(a),f.stops=[].concat(f.stops),s(d,function(a,b){f.stops[b]=[f.stops[b][0],a.get(c)]})):f=b&&!isNaN(b[0])?"rgb"===c?"rgb("+b[0]+","+b[1]+","+b[2]+")":"a"===c?b[3]:"rgba("+b.join(",")+")":a;return f},brighten:function(a){if(d)s(d,function(b){b.brighten(a)});
else if($(a)&&0!==a){var c;for(c=0;3>c;c++)b[c]+=B(255*a),0>b[c]&&(b[c]=0),255<b[c]&&(b[c]=255)}return this},rgba:b,setOpacity:function(a){b[3]=a;return this}}};K.prototype={opacity:1,textProps:"fontSize fontWeight fontFamily color lineHeight width textDecoration textShadow HcTextStroke".split(" "),init:function(a,b){this.element="span"===b?pa(b):A.createElementNS("http://www.w3.org/2000/svg",b);this.renderer=a},animate:function(a,b,c){b=r(b,R,!0);Oa(this);b?(b=D(b,{}),c&&(b.complete=c),kb(this,a,
b)):(this.attr(a),c&&c());return this},colorGradient:function(a,b,c){var d=this.renderer,e,f,g,h,k,l,m,p,q,n,t=[];a.linearGradient?f="linearGradient":a.radialGradient&&(f="radialGradient");if(f){g=a[f];h=d.gradients;l=a.stops;q=c.radialReference;ma(g)&&(a[f]=g={x1:g[0],y1:g[1],x2:g[2],y2:g[3],gradientUnits:"userSpaceOnUse"});"radialGradient"===f&&q&&!u(g.gradientUnits)&&(g=D(g,{cx:q[0]-q[2]/2+g.cx*q[2],cy:q[1]-q[2]/2+g.cy*q[2],r:g.r*q[2],gradientUnits:"userSpaceOnUse"}));for(n in g)"id"!==n&&t.push(n,
g[n]);for(n in l)t.push(l[n]);t=t.join(",");h[t]?a=h[t].attr("id"):(g.id=a="highcharts-"+Ma++,h[t]=k=d.createElement(f).attr(g).add(d.defs),k.stops=[],s(l,function(a){0===a[1].indexOf("rgba")?(e=ta(a[1]),m=e.get("rgb"),p=e.get("a")):(m=a[1],p=1);a=d.createElement("stop").attr({offset:a[0],"stop-color":m,"stop-opacity":p}).add(k);k.stops.push(a)}));c.setAttribute(b,"url("+d.url+"#"+a+")")}},attr:function(a,b){var c,d,e=this.element,f,g=this,h;"string"===typeof a&&b!==w&&(c=a,a={},a[c]=b);if("string"===
typeof a)g=(this[a+"Getter"]||this._defaultGetter).call(this,a,e);else{for(c in a)d=a[c],h=!1,this.symbolName&&/^(x|y|width|height|r|start|end|innerR|anchorX|anchorY)/.test(c)&&(f||(this.symbolAttr(a),f=!0),h=!0),!this.rotation||"x"!==c&&"y"!==c||(this.doTransform=!0),h||(this[c+"Setter"]||this._defaultSetter).call(this,d,c,e),this.shadows&&/^(width|height|visibility|x|y|d|transform|cx|cy|r)$/.test(c)&&this.updateShadows(c,d);this.doTransform&&(this.updateTransform(),this.doTransform=!1)}return g},
updateShadows:function(a,b){for(var c=this.shadows,d=c.length;d--;)c[d].setAttribute(a,"height"===a?v(b-(c[d].cutHeight||0),0):"d"===a?this.d:b)},addClass:function(a){var b=this.element,c=C(b,"class")||"";-1===c.indexOf(a)&&C(b,"class",c+" "+a);return this},symbolAttr:function(a){var b=this;s("x y r start end width height innerR anchorX anchorY".split(" "),function(c){b[c]=r(a[c],b[c])});b.attr({d:b.renderer.symbols[b.symbolName](b.x,b.y,b.width,b.height,b)})},clip:function(a){return this.attr("clip-path",
a?"url("+this.renderer.url+"#"+a.id+")":P)},crisp:function(a){var b,c={},d,e=a.strokeWidth||this.strokeWidth||0;d=z(e)%2/2;a.x=Q(a.x||this.x||0)+d;a.y=Q(a.y||this.y||0)+d;a.width=Q((a.width||this.width||0)-2*d);a.height=Q((a.height||this.height||0)-2*d);a.strokeWidth=e;for(b in a)this[b]!==a[b]&&(this[b]=c[b]=a[b]);return c},css:function(a){var b=this.styles,c={},d=this.element,e,f,g="";e=!b;a&&a.color&&(a.fill=a.color);if(b)for(f in a)a[f]!==b[f]&&(c[f]=a[f],e=!0);if(e){e=this.textWidth=a&&a.width&&
"text"===d.nodeName.toLowerCase()&&B(a.width);b&&(a=y(b,c));this.styles=a;e&&(Y||!O&&this.renderer.forExport)&&delete a.width;if(fa&&!O)N(this.element,a);else{b=function(a,b){return"-"+b.toLowerCase()};for(f in a)g+=f.replace(/([A-Z])/g,b)+":"+a[f]+";";C(d,"style",g)}e&&this.added&&this.renderer.buildText(this)}return this},on:function(a,b){this.element["on"+a]=b;return this},setRadialReference:function(a){this.element.radialReference=a;return this},translate:function(a,b){return this.attr({translateX:a,
translateY:b})},invert:function(){this.inverted=!0;this.updateTransform();return this},updateTransform:function(){var a=this.translateX||0,b=this.translateY||0,c=this.scaleX,d=this.scaleY,e=this.inverted,f=this.rotation,g=this.element;e&&(a+=this.attr("width"),b+=this.attr("height"));a=["translate("+a+","+b+")"];e?a.push("rotate(90) scale(-1,1)"):f&&a.push("rotate("+f+" "+(g.getAttribute("x")||0)+" "+(g.getAttribute("y")||0)+")");(u(c)||u(d))&&a.push("scale("+r(c,1)+" "+r(d,1)+")");a.length&&g.setAttribute("transform",
a.join(" "))},toFront:function(){var a=this.element;a.parentNode.appendChild(a);return this},align:function(a,b,c){var d,e,f,g,h={};e=this.renderer;f=e.alignedObjects;if(a){if(this.alignOptions=a,this.alignByTranslate=b,!c||ea(c))this.alignTo=d=c||"renderer",na(f,this),f.push(this),c=null}else a=this.alignOptions,b=this.alignByTranslate,d=this.alignTo;c=r(c,e[d],e);d=a.align;e=a.verticalAlign;f=(c.x||0)+(a.x||0);g=(c.y||0)+(a.y||0);if("right"===d||"center"===d)f+=(c.width-(a.width||0))/{right:1,center:2}[d];
h[b?"translateX":"x"]=z(f);if("bottom"===e||"middle"===e)g+=(c.height-(a.height||0))/({bottom:1,middle:2}[e]||1);h[b?"translateY":"y"]=z(g);this[this.placed?"animate":"attr"](h);this.placed=!0;this.alignAttr=h;return this},getBBox:function(){var a=this.bBox,b=this.renderer,c,d,e=this.rotation;c=this.element;var f=this.styles,g=e*eb;d=this.textStr;var h;if(""===d||qb.test(d))h="num."+d.toString().length+(f?"|"+f.fontSize+"|"+f.fontFamily:"");h&&(a=b.cache[h]);if(!a){if("http://www.w3.org/2000/svg"===
c.namespaceURI||b.forExport){try{a=c.getBBox?y({},c.getBBox()):{width:c.offsetWidth,height:c.offsetHeight}}catch(k){}if(!a||0>a.width)a={width:0,height:0}}else a=this.htmlGetBBox();b.isSVG&&(c=a.width,d=a.height,fa&&f&&"11px"===f.fontSize&&"16.9"===d.toPrecision(3)&&(a.height=d=14),e&&(a.width=W(d*Ca(g))+W(c*ra(g)),a.height=W(d*ra(g))+W(c*Ca(g))));this.bBox=a;h&&(b.cache[h]=a)}return a},show:function(a){return a&&"http://www.w3.org/2000/svg"===this.element.namespaceURI?(this.element.removeAttribute("visibility"),
this):this.attr({visibility:a?"inherit":"visible"})},hide:function(){return this.attr({visibility:"hidden"})},fadeOut:function(a){var b=this;b.animate({opacity:0},{duration:a||150,complete:function(){b.hide()}})},add:function(a){var b=this.renderer,c=a||b,d=c.element||b.box,e=this.element,f=this.zIndex,g,h;a&&(this.parentGroup=a);this.parentInverted=a&&a.inverted;void 0!==this.textStr&&b.buildText(this);f&&(c.handleZ=!0,f=B(f));if(c.handleZ)for(a=d.childNodes,g=0;g<a.length;g++)if(b=a[g],c=C(b,"zIndex"),
b!==e&&(B(c)>f||!u(f)&&u(c))){d.insertBefore(e,b);h=!0;break}h||d.appendChild(e);this.added=!0;if(this.onAdd)this.onAdd();return this},safeRemoveChild:function(a){var b=a.parentNode;b&&b.removeChild(a)},destroy:function(){var a=this,b=a.element||{},c=a.shadows,d=a.renderer.isSVG&&"SPAN"===b.nodeName&&a.parentGroup,e,f;b.onclick=b.onmouseout=b.onmouseover=b.onmousemove=b.point=null;Oa(a);a.clipPath&&(a.clipPath=a.clipPath.destroy());if(a.stops){for(f=0;f<a.stops.length;f++)a.stops[f]=a.stops[f].destroy();
a.stops=null}a.safeRemoveChild(b);for(c&&s(c,function(b){a.safeRemoveChild(b)});d&&d.div&&0===d.div.childNodes.length;)b=d.parentGroup,a.safeRemoveChild(d.div),delete d.div,d=b;a.alignTo&&na(a.renderer.alignedObjects,a);for(e in a)delete a[e];return null},shadow:function(a,b,c){var d=[],e,f,g=this.element,h,k,l,m;if(a){k=r(a.width,3);l=(a.opacity||.15)/k;m=this.parentInverted?"(-1,-1)":"("+r(a.offsetX,1)+", "+r(a.offsetY,1)+")";for(e=1;e<=k;e++)f=g.cloneNode(0),h=2*k+1-2*e,C(f,{isShadow:"true",stroke:a.color||
"black","stroke-opacity":l*e,"stroke-width":h,transform:"translate"+m,fill:P}),c&&(C(f,"height",v(C(f,"height")-h,0)),f.cutHeight=h),b?b.element.appendChild(f):g.parentNode.insertBefore(f,g),d.push(f);this.shadows=d}return this},xGetter:function(a){"circle"===this.element.nodeName&&(a={x:"cx",y:"cy"}[a]||a);return this._defaultGetter(a)},_defaultGetter:function(a){a=r(this[a],this.element?this.element.getAttribute(a):null,0);/^[\-0-9\.]+$/.test(a)&&(a=parseFloat(a));return a},dSetter:function(a,b,
c){a&&a.join&&(a=a.join(" "));/(NaN| {2}|^$)/.test(a)&&(a="M 0 0");c.setAttribute(b,a);this[b]=a},dashstyleSetter:function(a){var b;if(a=a&&a.toLowerCase()){a=a.replace("shortdashdotdot","3,1,1,1,1,1,").replace("shortdashdot","3,1,1,1").replace("shortdot","1,1,").replace("shortdash","3,1,").replace("longdash","8,3,").replace(/dot/g,"1,3,").replace("dash","4,3,").replace(/,$/,"").replace("solid",1).split(",");for(b=a.length;b--;)a[b]=B(a[b])*this["stroke-width"];a=a.join(",");this.element.setAttribute("stroke-dasharray",
a)}},alignSetter:function(a){this.element.setAttribute("text-anchor",{left:"start",center:"middle",right:"end"}[a])},opacitySetter:function(a,b,c){this[b]=a;c.setAttribute(b,a)},titleSetter:function(a){var b=this.element.getElementsByTagName("title")[0];b||(b=A.createElementNS("http://www.w3.org/2000/svg","title"),this.element.appendChild(b));b.textContent=a},textSetter:function(a){a!==this.textStr&&(delete this.bBox,this.textStr=a,this.added&&this.renderer.buildText(this))},fillSetter:function(a,
b,c){"string"===typeof a?c.setAttribute(b,a):a&&this.colorGradient(a,b,c)},zIndexSetter:function(a,b,c){c.setAttribute(b,a);this[b]=a},_defaultSetter:function(a,b,c){c.setAttribute(b,a)}};K.prototype.yGetter=K.prototype.xGetter;K.prototype.translateXSetter=K.prototype.translateYSetter=K.prototype.rotationSetter=K.prototype.verticalAlignSetter=K.prototype.scaleXSetter=K.prototype.scaleYSetter=function(a,b){this[b]=a;this.doTransform=!0};K.prototype["stroke-widthSetter"]=K.prototype.strokeSetter=function(a,
b,c){this[b]=a;this.stroke&&this["stroke-width"]?(this.strokeWidth=this["stroke-width"],K.prototype.fillSetter.call(this,this.stroke,"stroke",c),c.setAttribute("stroke-width",this["stroke-width"]),this.hasStroke=!0):"stroke-width"===b&&0===a&&this.hasStroke&&(c.removeAttribute("stroke"),this.hasStroke=!1)};var ua=function(){this.init.apply(this,arguments)};ua.prototype={Element:K,init:function(a,b,c,d,e){var f=location,g;d=this.createElement("svg").attr({version:"1.1"}).css(this.getStyle(d));g=d.element;
a.appendChild(g);-1===a.innerHTML.indexOf("xmlns")&&C(g,"xmlns","http://www.w3.org/2000/svg");this.isSVG=!0;this.box=g;this.boxWrapper=d;this.alignedObjects=[];this.url=(Da||ob)&&A.getElementsByTagName("base").length?f.href.replace(/#.*?$/,"").replace(/([\('\)])/g,"\\$1").replace(/ /g,"%20"):"";this.createElement("desc").add().element.appendChild(A.createTextNode("Created with Highcharts 4.0.3 /Highstock 2.0.3"));this.defs=this.createElement("defs").add();this.forExport=e;this.gradients={};this.cache=
{};this.setSize(b,c,!1);var h;Da&&a.getBoundingClientRect&&(this.subPixelFix=b=function(){N(a,{left:0,top:0});h=a.getBoundingClientRect();N(a,{left:ka(h.left)-h.left+"px",top:ka(h.top)-h.top+"px"})},b(),L(x,"resize",b))},getStyle:function(a){return this.style=y({fontFamily:'"Lucida Grande", "Lucida Sans Unicode", Arial, Helvetica, sans-serif',fontSize:"12px"},a)},isHidden:function(){return!this.boxWrapper.getBBox().width},destroy:function(){var a=this.defs;this.box=null;this.boxWrapper=this.boxWrapper.destroy();
ya(this.gradients||{});this.gradients=null;a&&(this.defs=a.destroy());this.subPixelFix&&T(x,"resize",this.subPixelFix);return this.alignedObjects=null},createElement:function(a){var b=new this.Element;b.init(this,a);return b},draw:function(){},buildText:function(a){for(var b=a.element,c=this,d=c.forExport,e=r(a.textStr,"").toString(),f=-1!==e.indexOf("<"),g=b.childNodes,h,k,l=C(b,"x"),m=a.styles,p=a.textWidth,q=m&&m.lineHeight,n=m&&m.HcTextStroke,t=g.length,H=function(a){return q?B(q):c.fontMetrics(/(px|em)$/.test(a&&
a.style.fontSize)?a.style.fontSize:m&&m.fontSize||c.style.fontSize||12,a).h};t--;)b.removeChild(g[t]);f||n||-1!==e.indexOf(" ")?(h=/<.*style="([^"]+)".*>/,k=/<.*href="(http[^"]+)".*>/,p&&!a.added&&this.box.appendChild(b),e=f?e.replace(/<(b|strong)>/g,'<span style="font-weight:bold">').replace(/<(i|em)>/g,'<span style="font-style:italic">').replace(/<a/g,"<span").replace(/<\/(b|strong|i|em|a)>/g,"</span>").split(/<br.*?>/g):[e],""===e[e.length-1]&&e.pop(),s(e,function(e,f){var g,n=0;e=e.replace(/<span/g,
"|||<span").replace(/<\/span>/g,"</span>|||");g=e.split("|||");s(g,function(e){if(""!==e||1===g.length){var q={},t=A.createElementNS("http://www.w3.org/2000/svg","tspan"),r;h.test(e)&&(r=e.match(h)[1].replace(/(;| |^)color([ :])/,"$1fill$2"),C(t,"style",r));k.test(e)&&!d&&(C(t,"onclick",'location.href="'+e.match(k)[1]+'"'),N(t,{cursor:"pointer"}));e=(e.replace(/<(.|\n)*?>/g,"")||" ").replace(/&lt;/g,"<").replace(/&gt;/g,">");if(" "!==e){t.appendChild(A.createTextNode(e));n?q.dx=0:f&&null!==l&&(q.x=
l);C(t,q);b.appendChild(t);!n&&f&&(!O&&d&&N(t,{display:"block"}),C(t,"dy",H(t)));if(p){e=e.replace(/([^\^])-/g,"$1- ").split(" ");for(var q=1<g.length||1<e.length&&"nowrap"!==m.whiteSpace,s,G,u=m.HcHeight,E=[],w=H(t),lb=1;q&&(e.length||E.length);)delete a.bBox,s=a.getBBox(),G=s.width,!O&&c.forExport&&(G=c.measureSpanWidth(t.firstChild.data,a.styles)),(s=G>p)&&1!==e.length?(t.removeChild(t.firstChild),E.unshift(e.pop())):(e=E,E=[],e.length&&(lb++,u&&lb*w>u?(e=["..."],a.attr("title",a.textStr)):(t=
A.createElementNS("http://www.w3.org/2000/svg","tspan"),C(t,{dy:w,x:l}),r&&C(t,"style",r),b.appendChild(t))),G>p&&(p=G)),e.length&&t.appendChild(A.createTextNode(e.join(" ").replace(/- /g,"-")))}n++}}})})):b.appendChild(A.createTextNode(e))},button:function(a,b,c,d,e,f,g,h,k){var l=this.label(a,b,c,k,null,null,null,null,"button"),m=0,p,q,n,t,r,s;a={x1:0,y1:0,x2:0,y2:1};e=D({"stroke-width":1,stroke:"#CCCCCC",fill:{linearGradient:a,stops:[[0,"#FEFEFE"],[1,"#F6F6F6"]]},r:2,padding:5,style:{color:"black"}},
e);n=e.style;delete e.style;f=D(e,{stroke:"#68A",fill:{linearGradient:a,stops:[[0,"#FFF"],[1,"#ACF"]]}},f);t=f.style;delete f.style;g=D(e,{stroke:"#68A",fill:{linearGradient:a,stops:[[0,"#9BD"],[1,"#CDF"]]}},g);r=g.style;delete g.style;h=D(e,{style:{color:"#CCC"}},h);s=h.style;delete h.style;L(l.element,fa?"mouseover":"mouseenter",function(){3!==m&&l.attr(f).css(t)});L(l.element,fa?"mouseout":"mouseleave",function(){3!==m&&(p=[e,f,g][m],q=[n,t,r][m],l.attr(p).css(q))});l.setState=function(a){(l.state=
m=a)?2===a?l.attr(g).css(r):3===a&&l.attr(h).css(s):l.attr(e).css(n)};return l.on("click",function(){3!==m&&d.call(l)}).attr(e).css(y({cursor:"default"},n))},crispLine:function(a,b){a[1]===a[4]&&(a[1]=a[4]=z(a[1])-b%2/2);a[2]===a[5]&&(a[2]=a[5]=z(a[2])+b%2/2);return a},path:function(a){var b={fill:P};ma(a)?b.d=a:Z(a)&&y(b,a);return this.createElement("path").attr(b)},circle:function(a,b,c){a=Z(a)?a:{x:a,y:b,r:c};b=this.createElement("circle");b.xSetter=function(a){this.element.setAttribute("cx",a)};
b.ySetter=function(a){this.element.setAttribute("cy",a)};return b.attr(a)},arc:function(a,b,c,d,e,f){Z(a)&&(b=a.y,c=a.r,d=a.innerR,e=a.start,f=a.end,a=a.x);a=this.symbol("arc",a||0,b||0,c||0,c||0,{innerR:d||0,start:e||0,end:f||0});a.r=c;return a},rect:function(a,b,c,d,e,f){e=Z(a)?a.r:e;var g=this.createElement("rect");a=Z(a)?a:a===w?{}:{x:a,y:b,width:v(c,0),height:v(d,0)};f!==w&&(a.strokeWidth=f,a=g.crisp(a));e&&(a.r=e);g.rSetter=function(a){C(this.element,{rx:a,ry:a})};return g.attr(a)},setSize:function(a,
b,c){var d=this.alignedObjects,e=d.length;this.width=a;this.height=b;for(this.boxWrapper[r(c,!0)?"animate":"attr"]({width:a,height:b});e--;)d[e].align()},g:function(a){var b=this.createElement("g");return u(a)?b.attr({"class":"highcharts-"+a}):b},image:function(a,b,c,d,e){var f={preserveAspectRatio:P};1<arguments.length&&y(f,{x:b,y:c,width:d,height:e});f=this.createElement("image").attr(f);f.element.setAttributeNS?f.element.setAttributeNS("http://www.w3.org/1999/xlink","href",a):f.element.setAttribute("hc-svg-href",
a);return f},symbol:function(a,b,c,d,e,f){var g,h=this.symbols[a],h=h&&h(z(b),z(c),d,e,f),k=/^url\((.*?)\)$/,l,m;h?(g=this.path(h),y(g,{symbolName:a,x:b,y:c,width:d,height:e}),f&&y(g,f)):k.test(a)&&(m=function(a,b){a.element&&(a.attr({width:b[0],height:b[1]}),a.alignByTranslate||a.translate(z((d-b[0])/2),z((e-b[1])/2)))},l=a.match(k)[1],a=gb[l],g=this.image(l).attr({x:b,y:c}),g.isImg=!0,a?m(g,a):(g.attr({width:0,height:0}),pa("img",{onload:function(){m(g,gb[l]=[this.width,this.height])},src:l})));
return g},symbols:{circle:function(a,b,c,d){var e=.166*c;return["M",a+c/2,b,"C",a+c+e,b,a+c+e,b+d,a+c/2,b+d,"C",a-e,b+d,a-e,b,a+c/2,b,"Z"]},square:function(a,b,c,d){return["M",a,b,"L",a+c,b,a+c,b+d,a,b+d,"Z"]},triangle:function(a,b,c,d){return["M",a+c/2,b,"L",a+c,b+d,a,b+d,"Z"]},"triangle-down":function(a,b,c,d){return["M",a,b,"L",a+c,b,a+c/2,b+d,"Z"]},diamond:function(a,b,c,d){return["M",a+c/2,b,"L",a+c,b+d/2,a+c/2,b+d,a,b+d/2,"Z"]},arc:function(a,b,c,d,e){var f=e.start;c=e.r||c||d;var g=e.end-.001;
d=e.innerR;var h=e.open,k=ra(f),l=Ca(f),m=ra(g),g=Ca(g);e=e.end-f<db?0:1;return["M",a+c*k,b+c*l,"A",c,c,0,e,1,a+c*m,b+c*g,h?"M":"L",a+d*m,b+d*g,"A",d,d,0,e,0,a+d*k,b+d*l,h?"":"Z"]},callout:function(a,b,c,d,e){var f=U(e&&e.r||0,c,d),g=f+6,h=e&&e.anchorX,k=e&&e.anchorY;e=z(e.strokeWidth||0)%2/2;a+=e;b+=e;e=["M",a+f,b,"L",a+c-f,b,"C",a+c,b,a+c,b,a+c,b+f,"L",a+c,b+d-f,"C",a+c,b+d,a+c,b+d,a+c-f,b+d,"L",a+f,b+d,"C",a,b+d,a,b+d,a,b+d-f,"L",a,b+f,"C",a,b,a,b,a+f,b];h&&h>c&&k>b+g&&k<b+d-g?e.splice(13,3,"L",
a+c,k-6,a+c+6,k,a+c,k+6,a+c,b+d-f):h&&0>h&&k>b+g&&k<b+d-g?e.splice(33,3,"L",a,k+6,a-6,k,a,k-6,a,b+f):k&&k>d&&h>a+g&&h<a+c-g?e.splice(23,3,"L",h+6,b+d,h,b+d+6,h-6,b+d,a+f,b+d):k&&0>k&&h>a+g&&h<a+c-g&&e.splice(3,3,"L",h-6,b,h,b-6,h+6,b,c-f,b);return e}},clipRect:function(a,b,c,d){var e="highcharts-"+Ma++,f=this.createElement("clipPath").attr({id:e}).add(this.defs);a=this.rect(a,b,c,d,0).add(f);a.id=e;a.clipPath=f;return a},text:function(a,b,c,d){var e=Y||!O&&this.forExport,f={};if(d&&!this.forExport)return this.html(a,
b,c);f.x=Math.round(b||0);c&&(f.y=Math.round(c));if(a||0===a)f.text=a;a=this.createElement("text").attr(f);e&&a.css({position:"absolute"});d||(a.xSetter=function(a,b,c){var d=c.getElementsByTagName("tspan"),e,f=c.getAttribute(b),q;for(q=0;q<d.length;q++)e=d[q],e.getAttribute(b)===f&&e.setAttribute(b,a);c.setAttribute(b,a)});return a},fontMetrics:function(a,b){a=a||this.style.fontSize;b&&x.getComputedStyle&&(b=b.element||b,a=x.getComputedStyle(b,"").fontSize);a=/px/.test(a)?B(a):/em/.test(a)?12*parseFloat(a):
12;var c=24>a?a+4:z(1.2*a),d=z(.8*c);return{h:c,b:d,f:a}},label:function(a,b,c,d,e,f,g,h,k){function l(){var a,b;a=t.element.style;E=(void 0===la||void 0===B||n.styles.textAlign)&&t.textStr&&t.getBBox();n.width=(la||E.width||0)+2*F+Ga;n.height=(B||E.height||0)+2*F;da=F+q.fontMetrics(a&&a.fontSize,t).b;x&&(r||(a=z(-v*F),b=h?-da:0,n.box=r=d?q.symbol(d,a,b,n.width,n.height,G):q.rect(a,b,n.width,n.height,0,G["stroke-width"]),r.attr("fill",P).add(n)),r.isImg||r.attr(y({width:z(n.width),height:z(n.height)},
G)),G=null)}function m(){var a=n.styles,a=a&&a.textAlign,b=Ga+F*(1-v),c;c=h?0:da;u(la)&&E&&("center"===a||"right"===a)&&(b+={center:.5,right:1}[a]*(la-E.width));if(b!==t.x||c!==t.y)t.attr("x",b),c!==w&&t.attr("y",c);t.x=b;t.y=c}function p(a,b){r?r.attr(a,b):G[a]=b}var q=this,n=q.g(k),t=q.text("",0,0,g).attr({zIndex:1}),r,E,v=0,F=3,Ga=0,la,B,A,Ra,C=0,G={},da,x;n.onAdd=function(){t.add(n);n.attr({text:a||"",x:b,y:c});r&&u(e)&&n.attr({anchorX:e,anchorY:f})};n.widthSetter=function(a){la=a};n.heightSetter=
function(a){B=a};n.paddingSetter=function(a){u(a)&&a!==F&&(F=a,m())};n.paddingLeftSetter=function(a){u(a)&&a!==Ga&&(Ga=a,m())};n.alignSetter=function(a){v={left:0,center:.5,right:1}[a]};n.textSetter=function(a){a!==w&&t.textSetter(a);l();m()};n["stroke-widthSetter"]=function(a,b){a&&(x=!0);C=a%2/2;p(b,a)};n.strokeSetter=n.fillSetter=n.rSetter=function(a,b){"fill"===b&&a&&(x=!0);p(b,a)};n.anchorXSetter=function(a,b){e=a;p(b,a+C-A)};n.anchorYSetter=function(a,b){f=a;p(b,a-Ra)};n.xSetter=function(a){n.x=
a;v&&(a-=v*((la||E.width)+F));A=z(a);n.attr("translateX",A)};n.ySetter=function(a){Ra=n.y=z(a);n.attr("translateY",Ra)};var I=n.css;return y(n,{css:function(a){if(a){var b={};a=D(a);s(n.textProps,function(c){a[c]!==w&&(b[c]=a[c],delete a[c])});t.css(b)}return I.call(n,a)},getBBox:function(){return{width:E.width+2*F,height:E.height+2*F,x:E.x-F,y:E.y-F}},shadow:function(a){r&&r.shadow(a);return n},destroy:function(){T(n.element,"mouseenter");T(n.element,"mouseleave");t&&(t=t.destroy());r&&(r=r.destroy());
K.prototype.destroy.call(n);n=q=l=m=p=null}})}};ja.prototype={addLabel:function(){var a=this.axis,b=a.options,c=a.chart,d=a.horiz,e=a.categories,f=a.names,g=this.pos,h=b.labels,k=h.rotation,l=a.tickPositions,d=d&&e&&!h.step&&!h.staggerLines&&!h.rotation&&c.plotWidth/l.length||!d&&(c.margin[3]||.33*c.chartWidth),m=g===l[0],p=g===l[l.length-1],q,f=e?r(e[g],f[g],g):g,e=this.label,n=l.info;a.isDatetimeAxis&&n&&(q=b.dateTimeLabelFormats[n.higherRanks[g]||n.unitName]);this.isFirst=m;this.isLast=p;b=a.labelFormatter.call({axis:a,
chart:c,isFirst:m,isLast:p,dateTimeLabelFormat:q,value:a.isLog?X(aa(f)):f});g=d&&{width:v(1,z(d-2*(h.padding||10)))+"px"};g=y(g,h.style);u(e)?e&&e.attr({text:b}).css(g):(q={align:a.labelAlign},$(k)&&(q.rotation=k),d&&h.ellipsis&&(g.HcHeight=a.len/l.length),this.label=e=u(b)&&h.enabled?c.renderer.text(b,0,0,h.useHTML).attr(q).css(g).add(a.labelGroup):null,a.tickBaseline=c.renderer.fontMetrics(h.style.fontSize,e).b,k&&2===a.side&&(a.tickBaseline*=ra(k*eb)));this.yOffset=e?r(h.y,a.tickBaseline+(2===
a.side?8:-(e.getBBox().height/2))):0},getLabelSize:function(){var a=this.label,b=this.axis;return a?a.getBBox()[b.horiz?"height":"width"]:0},getLabelSides:function(){var a=this.label.getBBox(),b=this.axis,c=b.horiz,d=b.options.labels,a=c?a.width:a.height,b=c?d.x-a*{left:0,center:.5,right:1}[b.labelAlign]:0;return[b,c?a+b:a]},handleOverflow:function(a,b){var c=!0,d=this.axis,e=this.isFirst,f=this.isLast,g=d.horiz?b.x:b.y,h=d.reversed,k=d.tickPositions,l=this.getLabelSides(),m=l[0],l=l[1],p,q,n,r=this.label.line||
0;p=d.labelEdge;q=d.justifyLabels&&(e||f);p[r]===w||g+m>p[r]?p[r]=g+l:q||(c=!1);if(q){p=(q=d.justifyToPlot)?d.pos:0;q=q?p+d.len:d.chart.chartWidth;do a+=e?1:-1,n=d.ticks[k[a]];while(k[a]&&(!n||!n.label||n.label.line!==r));d=n&&n.label.xy&&n.label.xy.x+n.getLabelSides()[e?0:1];e&&!h||f&&h?g+m<p&&(g=p-m,n&&g+l>d&&(c=!1)):g+l>q&&(g=q-l,n&&g+m<d&&(c=!1));b.x=g}return c},getPosition:function(a,b,c,d){var e=this.axis,f=e.chart,g=d&&f.oldChartHeight||f.chartHeight;return{x:a?e.translate(b+c,null,null,d)+
e.transB:e.left+e.offset+(e.opposite?(d&&f.oldChartWidth||f.chartWidth)-e.right-e.left:0),y:a?g-e.bottom+e.offset-(e.opposite?e.height:0):g-e.translate(b+c,null,null,d)-e.transB}},getLabelPosition:function(a,b,c,d,e,f,g,h){var k=this.axis,l=k.transA,m=k.reversed,p=k.staggerLines;a=a+e.x-(f&&d?f*l*(m?-1:1):0);b=b+this.yOffset-(f&&!d?f*l*(m?1:-1):0);p&&(c.line=g/(h||1)%p,b+=k.labelOffset/p*c.line);return{x:a,y:b}},getMarkPath:function(a,b,c,d,e,f){return f.crispLine(["M",a,b,"L",a+(e?0:-c),b+(e?c:0)],
d)},render:function(a,b,c){var d=this.axis,e=d.options,f=d.chart.renderer,g=d.horiz,h=this.type,k=this.label,l=this.pos,m=e.labels,p=this.gridLine,q=h?h+"Grid":"grid",n=h?h+"Tick":"tick",t=e[q+"LineWidth"],s=e[q+"LineColor"],u=e[q+"LineDashStyle"],v=e[n+"Length"],q=e[n+"Width"]||0,F=e[n+"Color"],y=e[n+"Position"],n=this.mark,z=m.step,B=!0,A=d.tickmarkOffset,x=this.getPosition(g,l,A,b),C=x.x,x=x.y,G=g&&C===d.pos+d.len||!g&&x===d.pos?-1:1;c=r(c,1);this.isActive=!0;if(t&&(l=d.getPlotLinePath(l+A,t*G,
b,!0),p===w&&(p={stroke:s,"stroke-width":t},u&&(p.dashstyle=u),h||(p.zIndex=1),b&&(p.opacity=0),this.gridLine=p=t?f.path(l).attr(p).add(d.gridGroup):null),!b&&p&&l))p[this.isNew?"attr":"animate"]({d:l,opacity:c});q&&v&&("inside"===y&&(v=-v),d.opposite&&(v=-v),h=this.getMarkPath(C,x,v,q*G,g,f),n?n.animate({d:h,opacity:c}):this.mark=f.path(h).attr({stroke:F,"stroke-width":q,opacity:c}).add(d.axisGroup));k&&!isNaN(C)&&(k.xy=x=this.getLabelPosition(C,x,k,g,m,A,a,z),this.isFirst&&!this.isLast&&!r(e.showFirstLabel,
1)||this.isLast&&!this.isFirst&&!r(e.showLastLabel,1)?B=!1:d.isRadial||m.step||m.rotation||b||0===c||(B=this.handleOverflow(a,x)),z&&a%z&&(B=!1),B&&!isNaN(x.y)?(x.opacity=c,k[this.isNew?"attr":"animate"](x),this.isNew=!1):k.attr("y",-9999))},destroy:function(){ya(this,this.axis)}};Ba.prototype={defaultOptions:{dateTimeLabelFormats:{millisecond:"%H:%M:%S.%L",second:"%H:%M:%S",minute:"%H:%M",hour:"%H:%M",day:"%e. %b",week:"%e. %b",month:"%b '%y",year:"%Y"},endOnTick:!1,gridLineColor:"#C0C0C0",labels:Pa,
lineColor:"#C0D0E0",lineWidth:1,minPadding:.01,maxPadding:.01,minorGridLineColor:"#E0E0E0",minorGridLineWidth:1,minorTickColor:"#A0A0A0",minorTickLength:2,minorTickPosition:"outside",startOfWeek:1,startOnTick:!1,tickColor:"#C0D0E0",tickLength:10,tickmarkPlacement:"between",tickPixelInterval:100,tickPosition:"outside",tickWidth:1,title:{align:"middle",style:{color:"#707070"}},type:"linear"},defaultYAxisOptions:{endOnTick:!0,gridLineWidth:1,tickPixelInterval:72,showLastLabel:!0,labels:{x:-8,y:3},lineWidth:0,
maxPadding:.05,minPadding:.05,startOnTick:!0,tickWidth:0,title:{rotation:270,text:"Values"},stackLabels:{enabled:!1,formatter:function(){return ga(this.total,-1)},style:Pa.style}},defaultLeftAxisOptions:{labels:{x:-15,y:null},title:{rotation:270}},defaultRightAxisOptions:{labels:{x:15,y:null},title:{rotation:90}},defaultBottomAxisOptions:{labels:{x:0,y:null},title:{rotation:0}},defaultTopAxisOptions:{labels:{x:0,y:-15},title:{rotation:0}},init:function(a,b){var c=b.isX;this.horiz=a.inverted?!c:c;
this.coll=(this.isXAxis=c)?"xAxis":"yAxis";this.opposite=b.opposite;this.side=b.side||(this.horiz?this.opposite?0:2:this.opposite?1:3);this.setOptions(b);var d=this.options,e=d.type;this.labelFormatter=d.labels.formatter||this.defaultLabelFormatter;this.userOptions=b;this.minPixelPadding=0;this.chart=a;this.reversed=d.reversed;this.zoomEnabled=!1!==d.zoomEnabled;this.categories=d.categories||"category"===e;this.names=[];this.isLog="logarithmic"===e;this.isDatetimeAxis="datetime"===e;this.isLinked=
u(d.linkedTo);this.tickmarkOffset=this.categories&&"between"===d.tickmarkPlacement?.5:0;this.ticks={};this.labelEdge=[];this.minorTicks={};this.plotLinesAndBands=[];this.alternateBands={};this.len=0;this.minRange=this.userMinRange=d.minRange||d.maxZoom;this.range=d.range;this.offset=d.offset||0;this.stacks={};this.oldStacks={};this.min=this.max=null;this.crosshair=r(d.crosshair,oa(a.options.tooltip.crosshairs)[c?0:1],!1);var f,d=this.options.events;-1===rb(this,a.axes)&&(c&&!this.isColorAxis?a.axes.splice(a.xAxis.length,
0,this):a.axes.push(this),a[this.coll].push(this));this.series=this.series||[];a.inverted&&c&&this.reversed===w&&(this.reversed=!0);this.removePlotLine=this.removePlotBand=this.removePlotBandOrLine;for(f in d)L(this,f,d[f]);this.isLog&&(this.val2lin=Ia,this.lin2val=aa)},setOptions:function(a){this.options=D(this.defaultOptions,this.isXAxis?{}:this.defaultYAxisOptions,[this.defaultTopAxisOptions,this.defaultRightAxisOptions,this.defaultBottomAxisOptions,this.defaultLeftAxisOptions][this.side],D(I[this.coll],
a))},defaultLabelFormatter:function(){var a=this.axis,b=this.value,c=a.categories,d=this.dateTimeLabelFormat,e=I.lang.numericSymbols,f=e&&e.length,g,h=a.options.labels.format,a=a.isLog?b:a.tickInterval;if(h)g=va(h,this);else if(c)g=b;else if(d)g=wa(d,b);else if(f&&1E3<=a)for(;f--&&g===w;)c=Math.pow(1E3,f+1),a>=c&&null!==e[f]&&(g=ga(b/c,-1)+e[f]);g===w&&(g=1E4<=W(b)?ga(b,0):ga(b,-1,w,""));return g},getSeriesExtremes:function(){var a=this,b=a.chart;a.hasVisibleSeries=!1;a.dataMin=a.dataMax=null;a.buildStacks&&
a.buildStacks();s(a.series,function(c){if(c.visible||!b.options.chart.ignoreHiddenSeries){var d;d=c.options.threshold;var e;a.hasVisibleSeries=!0;a.isLog&&0>=d&&(d=null);a.isXAxis?(d=c.xData,d.length&&(a.dataMin=U(r(a.dataMin,d[0]),xa(d)),a.dataMax=v(r(a.dataMax,d[0]),qa(d)))):(c.getExtremes(),e=c.dataMax,c=c.dataMin,u(c)&&u(e)&&(a.dataMin=U(r(a.dataMin,c),c),a.dataMax=v(r(a.dataMax,e),e)),u(d)&&(a.dataMin>=d?(a.dataMin=d,a.ignoreMinPadding=!0):a.dataMax<d&&(a.dataMax=d,a.ignoreMaxPadding=!0)))}})},
translate:function(a,b,c,d,e,f){var g=1,h=0,k=d?this.oldTransA:this.transA;d=d?this.oldMin:this.min;var l=this.minPixelPadding;e=(this.options.ordinal||this.isLog&&e)&&this.lin2val;k||(k=this.transA);c&&(g*=-1,h=this.len);this.reversed&&(g*=-1,h-=g*(this.sector||this.len));b?(a=a*g+h-l,a=a/k+d,e&&(a=this.lin2val(a))):(e&&(a=this.val2lin(a)),"between"===f&&(f=.5),a=g*(a-d)*k+h+g*l+($(f)?k*f*this.pointRange:0));return a},toPixels:function(a,b){return this.translate(a,!1,!this.horiz,null,!0)+(b?0:this.pos)},
toValue:function(a,b){return this.translate(a-(b?0:this.pos),!0,!this.horiz,null,!0)},getPlotLinePath:function(a,b,c,d,e){var f=this.chart,g=this.left,h=this.top,k,l,m=c&&f.oldChartHeight||f.chartHeight,p=c&&f.oldChartWidth||f.chartWidth,q;k=this.transB;e=r(e,this.translate(a,null,null,c));a=c=z(e+k);k=l=z(m-e-k);if(isNaN(e))q=!0;else if(this.horiz){if(k=h,l=m-this.bottom,a<g||a>g+this.width)q=!0}else if(a=g,c=p-this.right,k<h||k>h+this.height)q=!0;return q&&!d?null:f.renderer.crispLine(["M",a,k,
"L",c,l],b||1)},getLinearTickPositions:function(a,b,c){var d,e=X(Q(b/a)*a),f=X(ka(c/a)*a),g=[];if(b===c&&$(b))return[b];for(b=e;b<=f;){g.push(b);b=X(b+a);if(b===d)break;d=b}return g},getMinorTickPositions:function(){var a=this.options,b=this.tickPositions,c=this.minorTickInterval,d=[],e;if(this.isLog)for(e=b.length,a=1;a<e;a++)d=d.concat(this.getLogTickPositions(c,b[a-1],b[a],!0));else if(this.isDatetimeAxis&&"auto"===a.minorTickInterval)d=d.concat(this.getTimeTicks(this.normalizeTimeTickInterval(c),
this.min,this.max,a.startOfWeek)),d[0]<this.min&&d.shift();else for(b=this.min+(b[0]-this.min)%c;b<=this.max;b+=c)d.push(b);return d},adjustForMinRange:function(){var a=this.options,b=this.min,c=this.max,d,e=this.dataMax-this.dataMin>=this.minRange,f,g,h,k,l;this.isXAxis&&this.minRange===w&&!this.isLog&&(u(a.min)||u(a.max)?this.minRange=null:(s(this.series,function(a){k=a.xData;for(g=l=a.xIncrement?1:k.length-1;0<g;g--)if(h=k[g]-k[g-1],f===w||h<f)f=h}),this.minRange=U(5*f,this.dataMax-this.dataMin)));
if(c-b<this.minRange){var m=this.minRange;d=(m-c+b)/2;d=[b-d,r(a.min,b-d)];e&&(d[2]=this.dataMin);b=qa(d);c=[b+m,r(a.max,b+m)];e&&(c[2]=this.dataMax);c=xa(c);c-b<m&&(d[0]=c-m,d[1]=r(a.min,c-m),b=qa(d))}this.min=b;this.max=c},setAxisTranslation:function(a){var b=this,c=b.max-b.min,d=b.axisPointRange||0,e,f=0,g=0,h=b.linkedParent,k=!!b.categories,l=b.transA;if(b.isXAxis||k||d)h?(f=h.minPointOffset,g=h.pointRangePadding):s(b.series,function(a){var h=k?1:b.isXAxis?a.pointRange:b.axisPointRange||0,l=a.options.pointPlacement,
n=a.closestPointRange;h>c&&(h=0);d=v(d,h);f=v(f,ea(l)?0:h/2);g=v(g,"on"===l?0:h);!a.noSharedTooltip&&u(n)&&(e=u(e)?U(e,n):n)}),h=b.ordinalSlope&&e?b.ordinalSlope/e:1,b.minPointOffset=f*=h,b.pointRangePadding=g*=h,b.pointRange=U(d,c),b.closestPointRange=e;a&&(b.oldTransA=l);b.translationSlope=b.transA=l=b.len/(c+g||1);b.transB=b.horiz?b.left:b.bottom;b.minPixelPadding=l*f},setTickPositions:function(a){var b=this,c=b.chart,d=b.options,e=d.startOnTick,f=d.endOnTick,g=b.isLog,h=b.isDatetimeAxis,k=b.isXAxis,
l=b.isLinked,m=b.options.tickPositioner,p=d.maxPadding,q=d.minPadding,n=d.tickInterval,t=d.minTickInterval,H=d.tickPixelInterval,E,w=b.categories;l?(b.linkedParent=c[b.coll][d.linkedTo],c=b.linkedParent.getExtremes(),b.min=r(c.min,c.dataMin),b.max=r(c.max,c.dataMax),d.type!==b.linkedParent.options.type&&S(11,1)):(b.min=r(b.userMin,d.min,b.dataMin),b.max=r(b.userMax,d.max,b.dataMax));g&&(!a&&0>=U(b.min,r(b.dataMin,b.min))&&S(10,1),b.min=X(Ia(b.min)),b.max=X(Ia(b.max)));b.range&&u(b.max)&&(b.userMin=
b.min=v(b.min,b.max-b.range),b.userMax=b.max,b.range=null);b.beforePadding&&b.beforePadding();b.adjustForMinRange();!(w||b.axisPointRange||b.usePercentage||l)&&u(b.min)&&u(b.max)&&(c=b.max-b.min)&&(u(d.min)||u(b.userMin)||!q||!(0>b.dataMin)&&b.ignoreMinPadding||(b.min-=c*q),u(d.max)||u(b.userMax)||!p||!(0<b.dataMax)&&b.ignoreMaxPadding||(b.max+=c*p));$(d.floor)&&(b.min=v(b.min,d.floor));$(d.ceiling)&&(b.max=U(b.max,d.ceiling));b.min===b.max||void 0===b.min||void 0===b.max?b.tickInterval=1:l&&!n&&
H===b.linkedParent.options.tickPixelInterval?b.tickInterval=b.linkedParent.tickInterval:(b.tickInterval=r(n,w?1:(b.max-b.min)*H/v(b.len,H)),!u(n)&&b.len<H&&!this.isRadial&&!this.isLog&&!w&&e&&f&&(E=!0,b.tickInterval/=4));k&&!a&&s(b.series,function(a){a.processData(b.min!==b.oldMin||b.max!==b.oldMax)});b.setAxisTranslation(!0);b.beforeSetTickPositions&&b.beforeSetTickPositions();b.postProcessTickInterval&&(b.tickInterval=b.postProcessTickInterval(b.tickInterval));b.pointRange&&(b.tickInterval=v(b.pointRange,
b.tickInterval));!n&&b.tickInterval<t&&(b.tickInterval=t);h||g||n||(b.tickInterval=mb(b.tickInterval,null,J.pow(10,Q(J.log(b.tickInterval)/J.LN10)),d));b.minorTickInterval="auto"===d.minorTickInterval&&b.tickInterval?b.tickInterval/5:d.minorTickInterval;b.tickPositions=a=d.tickPositions?[].concat(d.tickPositions):m&&m.apply(b,[b.min,b.max]);a||(!b.ordinalPositions&&(b.max-b.min)/b.tickInterval>v(2*b.len,200)&&S(19,!0),a=h?b.getTimeTicks(b.normalizeTimeTickInterval(b.tickInterval,d.units),b.min,b.max,
d.startOfWeek,b.ordinalPositions,b.closestPointRange,!0):g?b.getLogTickPositions(b.tickInterval,b.min,b.max):b.getLinearTickPositions(b.tickInterval,b.min,b.max),E&&a.splice(1,a.length-2),b.tickPositions=a);l||(d=a[0],g=a[a.length-1],h=b.minPointOffset||0,e||f||w||2!==a.length||a.splice(1,0,(g+d)/2),e?b.min=d:b.min-h>d&&a.shift(),f?b.max=g:b.max+h<g&&a.pop(),1===a.length&&(e=1E13<W(b.max)?1:.001,b.min-=e,b.max+=e))},setMaxTicks:function(){var a=this.chart,b=a.maxTicks||{},c=this.tickPositions,d=this._maxTicksKey=
[this.coll,this.pos,this.len].join("-");!this.isLinked&&!this.isDatetimeAxis&&c&&c.length>(b[d]||0)&&!1!==this.options.alignTicks&&(b[d]=c.length);a.maxTicks=b},adjustTickAmount:function(){var a=this._maxTicksKey,b=this.tickPositions,c=this.chart.maxTicks;if(c&&c[a]&&!this.isDatetimeAxis&&!this.categories&&!this.isLinked&&!1!==this.options.alignTicks&&this.min!==w){var d=this.tickAmount,e=b.length;this.tickAmount=a=c[a];if(e<a){for(;b.length<a;)b.push(X(b[b.length-1]+this.tickInterval));this.transA*=
(e-1)/(a-1);this.max=b[b.length-1]}u(d)&&a!==d&&(this.isDirty=!0)}},setScale:function(){var a=this.stacks,b,c,d,e;this.oldMin=this.min;this.oldMax=this.max;this.oldAxisLength=this.len;this.setAxisSize();e=this.len!==this.oldAxisLength;s(this.series,function(a){if(a.isDirtyData||a.isDirty||a.xAxis.isDirty)d=!0});if(e||d||this.isLinked||this.forceRedraw||this.userMin!==this.oldUserMin||this.userMax!==this.oldUserMax){if(!this.isXAxis)for(b in a)for(c in a[b])a[b][c].total=null,a[b][c].cum=0;this.forceRedraw=
!1;this.getSeriesExtremes();this.setTickPositions();this.oldUserMin=this.userMin;this.oldUserMax=this.userMax;this.isDirty||(this.isDirty=e||this.min!==this.oldMin||this.max!==this.oldMax)}else if(!this.isXAxis)for(b in this.oldStacks&&(a=this.stacks=this.oldStacks),a)for(c in a[b])a[b][c].cum=a[b][c].total;this.setMaxTicks()},setExtremes:function(a,b,c,d,e){var f=this,g=f.chart;c=r(c,!0);e=y(e,{min:a,max:b});M(f,"setExtremes",e,function(){f.userMin=a;f.userMax=b;f.eventArgs=e;f.isDirtyExtremes=!0;
c&&g.redraw(d)})},zoom:function(a,b){var c=this.dataMin,d=this.dataMax,e=this.options;this.allowZoomOutside||(u(c)&&a<=U(c,r(e.min,c))&&(a=w),u(d)&&b>=v(d,r(e.max,d))&&(b=w));this.displayBtn=a!==w||b!==w;this.setExtremes(a,b,!1,w,{trigger:"zoom"});return!0},setAxisSize:function(){var a=this.chart,b=this.options,c=b.offsetLeft||0,d=this.horiz,e=r(b.width,a.plotWidth-c+(b.offsetRight||0)),f=r(b.height,a.plotHeight),g=r(b.top,a.plotTop),b=r(b.left,a.plotLeft+c),c=/%$/;c.test(f)&&(f=parseInt(f,10)/100*
a.plotHeight);c.test(g)&&(g=parseInt(g,10)/100*a.plotHeight+a.plotTop);this.left=b;this.top=g;this.width=e;this.height=f;this.bottom=a.chartHeight-f-g;this.right=a.chartWidth-e-b;this.len=v(d?e:f,0);this.pos=d?b:g},getExtremes:function(){var a=this.isLog;return{min:a?X(aa(this.min)):this.min,max:a?X(aa(this.max)):this.max,dataMin:this.dataMin,dataMax:this.dataMax,userMin:this.userMin,userMax:this.userMax}},getThreshold:function(a){var b=this.isLog,c=b?aa(this.min):this.min,b=b?aa(this.max):this.max;
c>a||null===a?a=c:b<a&&(a=b);return this.translate(a,0,1,0,1)},autoLabelAlign:function(a){a=(r(a,0)-90*this.side+720)%360;return 15<a&&165>a?"right":195<a&&345>a?"left":"center"},getOffset:function(){var a=this,b=a.chart,c=b.renderer,d=a.options,e=a.tickPositions,f=a.ticks,g=a.horiz,h=a.side,k=b.inverted?[1,0,3,2][h]:h,l,m,p=0,q,n=0,t=d.title,H=d.labels,E=0,z=b.axisOffset,b=b.clipOffset,F=[-1,1,1,-1][h],x,y=1,B=r(H.maxStaggerLines,5),A,C,D,G,da;a.hasData=l=a.hasVisibleSeries||u(a.min)&&u(a.max)&&
!!e;a.showAxis=m=l||r(d.showEmpty,!0);a.staggerLines=a.horiz&&H.staggerLines;a.axisGroup||(a.gridGroup=c.g("grid").attr({zIndex:d.gridZIndex||1}).add(),a.axisGroup=c.g("axis").attr({zIndex:d.zIndex||2}).add(),a.labelGroup=c.g("axis-labels").attr({zIndex:H.zIndex||7}).addClass("highcharts-"+a.coll.toLowerCase()+"-labels").add());if(l||a.isLinked){a.labelAlign=r(H.align||a.autoLabelAlign(H.rotation));s(e,function(b){f[b]?f[b].addLabel():f[b]=new ja(a,b)});if(a.horiz&&!a.staggerLines&&B&&!H.rotation){for(l=
a.reversed?[].concat(e).reverse():e;y<B;){A=[];C=!1;for(x=0;x<l.length;x++)D=l[x],G=(G=f[D].label&&f[D].label.getBBox())?G.width:0,da=x%y,G&&(D=a.translate(D),A[da]!==w&&D<A[da]&&(C=!0),A[da]=D+G);if(C)y++;else break}1<y&&(a.staggerLines=y)}s(e,function(b){if(0===h||2===h||{1:"left",3:"right"}[h]===a.labelAlign)E=v(f[b].getLabelSize(),E)});a.staggerLines&&(E*=a.staggerLines,a.labelOffset=E)}else for(x in f)f[x].destroy(),delete f[x];t&&t.text&&!1!==t.enabled&&(a.axisTitle||(a.axisTitle=c.text(t.text,
0,0,t.useHTML).attr({zIndex:7,rotation:t.rotation||0,align:t.textAlign||{low:"left",middle:"center",high:"right"}[t.align]}).addClass("highcharts-"+this.coll.toLowerCase()+"-title").css(t.style).add(a.axisGroup),a.axisTitle.isNew=!0),m&&(p=a.axisTitle.getBBox()[g?"height":"width"],q=t.offset,n=u(q)?0:r(t.margin,g?5:10)),a.axisTitle[m?"show":"hide"]());a.offset=F*r(d.offset,z[h]);c=2===h?a.tickBaseline:0;g=E+n+(E&&F*(g?r(H.y,a.tickBaseline+8):H.x)-c);a.axisTitleMargin=r(q,g);z[h]=v(z[h],a.axisTitleMargin+
p+F*a.offset,g);b[k]=v(b[k],2*Q(d.lineWidth/2))},getLinePath:function(a){var b=this.chart,c=this.opposite,d=this.offset,e=this.horiz,f=this.left+(c?this.width:0)+d,d=b.chartHeight-this.bottom-(c?this.height:0)+d;c&&(a*=-1);return b.renderer.crispLine(["M",e?this.left:f,e?d:this.top,"L",e?b.chartWidth-this.right:f,e?d:b.chartHeight-this.bottom],a)},getTitlePosition:function(){var a=this.horiz,b=this.left,c=this.top,d=this.len,e=this.options.title,f=a?b:c,g=this.opposite,h=this.offset,k=B(e.style.fontSize||
12),d={low:f+(a?0:d),middle:f+d/2,high:f+(a?d:0)}[e.align],b=(a?c+this.height:b)+(a?1:-1)*(g?-1:1)*this.axisTitleMargin+(2===this.side?k:0);return{x:a?d:b+(g?this.width:0)+h+(e.x||0),y:a?b-(g?this.height:0)+h:d+(e.y||0)}},render:function(){var a=this,b=a.horiz,c=a.reversed,d=a.chart,e=d.renderer,f=a.options,g=a.isLog,h=a.isLinked,k=a.tickPositions,l,m=a.axisTitle,p=a.ticks,q=a.minorTicks,n=a.alternateBands,r=f.stackLabels,H=f.alternateGridColor,v=a.tickmarkOffset,x=f.lineWidth,F=d.hasRendered&&u(a.oldMin)&&
!isNaN(a.oldMin),y=a.hasData,z=a.showAxis,A,B=f.labels.overflow,C=a.justifyLabels=b&&!1!==B,D;a.labelEdge.length=0;a.justifyToPlot="justify"===B;s([p,q,n],function(a){for(var b in a)a[b].isActive=!1});if(y||h)a.minorTickInterval&&!a.categories&&s(a.getMinorTickPositions(),function(b){q[b]||(q[b]=new ja(a,b,"minor"));F&&q[b].isNew&&q[b].render(null,!0);q[b].render(null,!1,1)}),k.length&&(l=k.slice(),(b&&c||!b&&!c)&&l.reverse(),C&&(l=l.slice(1).concat([l[0]])),s(l,function(b,c){C&&(c=c===l.length-1?
0:c+1);if(!h||b>=a.min&&b<=a.max)p[b]||(p[b]=new ja(a,b)),F&&p[b].isNew&&p[b].render(c,!0,.1),p[b].render(c)}),v&&0===a.min&&(p[-1]||(p[-1]=new ja(a,-1,null,!0)),p[-1].render(-1))),H&&s(k,function(b,c){0===c%2&&b<a.max&&(n[b]||(n[b]=new ca.PlotLineOrBand(a)),A=b+v,D=k[c+1]!==w?k[c+1]+v:a.max,n[b].options={from:g?aa(A):A,to:g?aa(D):D,color:H},n[b].render(),n[b].isActive=!0)}),a._addedPlotLB||(s((f.plotLines||[]).concat(f.plotBands||[]),function(b){a.addPlotBandOrLine(b)}),a._addedPlotLB=!0);s([p,q,
n],function(a){var b,c,e=[],f=R?R.duration||500:0,g=function(){for(c=e.length;c--;)a[e[c]]&&!a[e[c]].isActive&&(a[e[c]].destroy(),delete a[e[c]])};for(b in a)a[b].isActive||(a[b].render(b,!1,0),a[b].isActive=!1,e.push(b));a!==n&&d.hasRendered&&f?f&&setTimeout(g,f):g()});x&&(b=a.getLinePath(x),a.axisLine?a.axisLine.animate({d:b}):a.axisLine=e.path(b).attr({stroke:f.lineColor,"stroke-width":x,zIndex:7}).add(a.axisGroup),a.axisLine[z?"show":"hide"]());m&&z&&(m[m.isNew?"attr":"animate"](a.getTitlePosition()),
m.isNew=!1);r&&r.enabled&&a.renderStackTotals();a.isDirty=!1},redraw:function(){this.render();s(this.plotLinesAndBands,function(a){a.render()});s(this.series,function(a){a.isDirty=!0})},destroy:function(a){var b=this,c=b.stacks,d,e=b.plotLinesAndBands;a||T(b);for(d in c)ya(c[d]),c[d]=null;s([b.ticks,b.minorTicks,b.alternateBands],function(a){ya(a)});for(a=e.length;a--;)e[a].destroy();s("stackTotalGroup axisLine axisTitle axisGroup cross gridGroup labelGroup".split(" "),function(a){b[a]&&(b[a]=b[a].destroy())});
this.cross&&this.cross.destroy()},drawCrosshair:function(a,b){if(this.crosshair)if(!1===(u(b)||!r(this.crosshair.snap,!0)))this.hideCrosshair();else{var c,d=this.crosshair,e=d.animation;r(d.snap,!0)?u(b)&&(c=this.chart.inverted!=this.horiz?b.plotX:this.len-b.plotY):c=this.horiz?a.chartX-this.pos:this.len-a.chartY+this.pos;c=this.isRadial?this.getPlotLinePath(this.isXAxis?b.x:r(b.stackY,b.y)):this.getPlotLinePath(null,null,null,null,c);if(null===c)this.hideCrosshair();else if(this.cross)this.cross.attr({visibility:"visible"})[e?
"animate":"attr"]({d:c},e);else e={"stroke-width":d.width||1,stroke:d.color||"#C0C0C0",zIndex:d.zIndex||2},d.dashStyle&&(e.dashstyle=d.dashStyle),this.cross=this.chart.renderer.path(c).attr(e).add()}},hideCrosshair:function(){this.cross&&this.cross.hide()}};y(Ba.prototype,void 0);var Sa=ca.Legend=function(a,b){this.init(a,b)};Sa.prototype={init:function(a,b){var c=this,d=b.itemStyle,e=r(b.padding,8),f=b.itemMarginTop||0;this.options=b;b.enabled&&(c.itemStyle=d,c.itemHiddenStyle=D(d,b.itemHiddenStyle),
c.itemMarginTop=f,c.padding=e,c.initialItemX=e,c.initialItemY=e-5,c.maxItemWidth=0,c.chart=a,c.itemHeight=0,c.lastLineHeight=0,c.symbolWidth=r(b.symbolWidth,16),c.pages=[],c.render(),L(c.chart,"endResize",function(){c.positionCheckboxes()}))},colorizeItem:function(a,b){var c=this.options,d=a.legendItem,e=a.legendLine,f=a.legendSymbol,g=this.itemHiddenStyle.color,c=b?c.itemStyle.color:g,h=b?a.legendColor||a.color||"#CCC":g,g=a.options&&a.options.marker,k={fill:h},l;d&&d.css({fill:c,color:c});e&&e.attr({stroke:h});
if(f){if(g&&f.isMarker)for(l in k.stroke=h,g=a.convertAttribs(g),g)d=g[l],d!==w&&(k[l]=d);f.attr(k)}},positionItem:function(a){var b=this.options,c=b.symbolPadding,b=!b.rtl,d=a._legendItemPos,e=d[0],d=d[1],f=a.checkbox;a.legendGroup&&a.legendGroup.translate(b?e:this.legendWidth-e-2*c-4,d);f&&(f.x=e,f.y=d)},destroyItem:function(a){var b=a.checkbox;s(["legendItem","legendLine","legendSymbol","legendGroup"],function(b){a[b]&&(a[b]=a[b].destroy())});b&&za(a.checkbox)},destroy:function(){var a=this.group,
b=this.box;b&&(this.box=b.destroy());a&&(this.group=a.destroy())},positionCheckboxes:function(a){var b=this.group.alignAttr,c,d=this.clipHeight||this.legendHeight;b&&(c=b.translateY,s(this.allItems,function(e){var f=e.checkbox,g;f&&(g=c+f.y+(a||0)+3,N(f,{left:b.translateX+e.checkboxOffset+f.x-20+"px",top:g+"px",display:g>c-6&&g<c+d-6?"":P}))}))},renderTitle:function(){var a=this.padding,b=this.options.title,c=0;b.text&&(this.title||(this.title=this.chart.renderer.label(b.text,a-3,a-4,null,null,null,
null,null,"legend-title").attr({zIndex:1}).css(b.style).add(this.group)),a=this.title.getBBox(),c=a.height,this.offsetWidth=a.width,this.contentGroup.attr({translateY:c}));this.titleHeight=c},renderItem:function(a){var b=this.chart,c=b.renderer,d=this.options,e="horizontal"===d.layout,f=this.symbolWidth,g=d.symbolPadding,h=this.itemStyle,k=this.itemHiddenStyle,l=this.padding,m=e?r(d.itemDistance,20):0,p=!d.rtl,q=d.width,n=d.itemMarginBottom||0,t=this.itemMarginTop,s=this.initialItemX,u=a.legendItem,
w=a.series&&a.series.drawLegendSymbol?a.series:a,x=w.options,x=this.createCheckboxForItem&&x&&x.showCheckbox,y=d.useHTML;u||(a.legendGroup=c.g("legend-item").attr({zIndex:1}).add(this.scrollGroup),a.legendItem=u=c.text(d.labelFormat?va(d.labelFormat,a):d.labelFormatter.call(a),p?f+g:-g,this.baseline||0,y).css(D(a.visible?h:k)).attr({align:p?"left":"right",zIndex:2}).add(a.legendGroup),this.baseline||(this.baseline=c.fontMetrics(h.fontSize,u).f+3+t,u.attr("y",this.baseline)),w.drawLegendSymbol(this,
a),this.setItemEvents&&this.setItemEvents(a,u,y,h,k),this.colorizeItem(a,a.visible),x&&this.createCheckboxForItem(a));c=u.getBBox();f=a.checkboxOffset=d.itemWidth||a.legendItemWidth||f+g+c.width+m+(x?20:0);this.itemHeight=g=z(a.legendItemHeight||c.height);e&&this.itemX-s+f>(q||b.chartWidth-2*l-s-d.x)&&(this.itemX=s,this.itemY+=t+this.lastLineHeight+n,this.lastLineHeight=0);this.maxItemWidth=v(this.maxItemWidth,f);this.lastItemY=t+this.itemY+n;this.lastLineHeight=v(g,this.lastLineHeight);a._legendItemPos=
[this.itemX,this.itemY];e?this.itemX+=f:(this.itemY+=t+g+n,this.lastLineHeight=g);this.offsetWidth=q||v((e?this.itemX-s-m:f)+l,this.offsetWidth)},getAllItems:function(){var a=[];s(this.chart.series,function(b){var c=b.options;r(c.showInLegend,u(c.linkedTo)?!1:w,!0)&&(a=a.concat(b.legendItems||("point"===c.legendType?b.data:b)))});return a},render:function(){var a=this,b=a.chart,c=b.renderer,d=a.group,e,f,g,h,k=a.box,l=a.options,m=a.padding,p=l.borderWidth,q=l.backgroundColor;a.itemX=a.initialItemX;
a.itemY=a.initialItemY;a.offsetWidth=0;a.lastItemY=0;d||(a.group=d=c.g("legend").attr({zIndex:7}).add(),a.contentGroup=c.g().attr({zIndex:1}).add(d),a.scrollGroup=c.g().add(a.contentGroup));a.renderTitle();e=a.getAllItems();Ka(e,function(a,b){return(a.options&&a.options.legendIndex||0)-(b.options&&b.options.legendIndex||0)});l.reversed&&e.reverse();a.allItems=e;a.display=f=!!e.length;s(e,function(b){a.renderItem(b)});g=l.width||a.offsetWidth;h=a.lastItemY+a.lastLineHeight+a.titleHeight;h=a.handleOverflow(h);
if(p||q)g+=m,h+=m,k?0<g&&0<h&&(k[k.isNew?"attr":"animate"](k.crisp({width:g,height:h})),k.isNew=!1):(a.box=k=c.rect(0,0,g,h,l.borderRadius,p||0).attr({stroke:l.borderColor,"stroke-width":p||0,fill:q||P}).add(d).shadow(l.shadow),k.isNew=!0),k[f?"show":"hide"]();a.legendWidth=g;a.legendHeight=h;s(e,function(b){a.positionItem(b)});f&&d.align(y({width:g,height:h},l),!0,"spacingBox");b.isResizing||this.positionCheckboxes()},handleOverflow:function(a){var b=this,c=this.chart,d=c.renderer,e=this.options,
f=e.y,f=c.spacingBox.height+("top"===e.verticalAlign?-f:f)-this.padding,g=e.maxHeight,h,k=this.clipRect,l=e.navigation,m=r(l.animation,!0),p=l.arrowSize||12,q=this.nav,n=this.pages,t,u=this.allItems;"horizontal"===e.layout&&(f/=2);g&&(f=U(f,g));n.length=0;a>f&&!e.useHTML?(this.clipHeight=h=v(f-20-this.titleHeight-this.padding,0),this.currentPage=r(this.currentPage,1),this.fullHeight=a,s(u,function(a,b){var c=a._legendItemPos[1],d=z(a.legendItem.getBBox().height),e=n.length;if(!e||c-n[e-1]>h&&(t||
c)!==n[e-1])n.push(t||c),e++;b===u.length-1&&c+d-n[e-1]>h&&n.push(c);c!==t&&(t=c)}),k||(k=b.clipRect=d.clipRect(0,this.padding,9999,0),b.contentGroup.clip(k)),k.attr({height:h}),q||(this.nav=q=d.g().attr({zIndex:1}).add(this.group),this.up=d.symbol("triangle",0,0,p,p).on("click",function(){b.scroll(-1,m)}).add(q),this.pager=d.text("",15,10).css(l.style).add(q),this.down=d.symbol("triangle-down",0,0,p,p).on("click",function(){b.scroll(1,m)}).add(q)),b.scroll(0),a=f):q&&(k.attr({height:c.chartHeight}),
q.hide(),this.scrollGroup.attr({translateY:1}),this.clipHeight=0);return a},scroll:function(a,b){var c=this.pages,d=c.length,e=this.currentPage+a,f=this.clipHeight,g=this.options.navigation,h=g.activeColor,g=g.inactiveColor,k=this.pager,l=this.padding;e>d&&(e=d);0<e&&(b!==w&&(R=r(b,this.chart.animation)),this.nav.attr({translateX:l,translateY:f+this.padding+7+this.titleHeight,visibility:"visible"}),this.up.attr({fill:1===e?g:h}).css({cursor:1===e?"default":"pointer"}),k.attr({text:e+"/"+d}),this.down.attr({x:18+
this.pager.getBBox().width,fill:e===d?g:h}).css({cursor:e===d?"default":"pointer"}),c=-c[e-1]+this.initialItemY,this.scrollGroup.animate({translateY:c}),this.currentPage=e,this.positionCheckboxes(c))}};var vb=ca.LegendSymbolMixin={drawRectangle:function(a,b){var c=a.options.symbolHeight||12;b.legendSymbol=this.chart.renderer.rect(0,a.baseline-5-c/2,a.symbolWidth,c,a.options.symbolRadius||0).attr({zIndex:3}).add(b.legendGroup)},drawLineMarker:function(a){var b=this.options,c=b.marker,d;d=a.symbolWidth;
var e=this.chart.renderer,f=this.legendGroup;a=a.baseline-z(.3*e.fontMetrics(a.options.itemStyle.fontSize,this.legendItem).b);var g;b.lineWidth&&(g={"stroke-width":b.lineWidth},b.dashStyle&&(g.dashstyle=b.dashStyle),this.legendLine=e.path(["M",0,a,"L",d,a]).attr(g).add(f));c&&!1!==c.enabled&&(b=c.radius,this.legendSymbol=d=e.symbol(this.symbol,d/2-b,a-b,2*b,2*b).add(f),d.isMarker=!0)}};(/Trident\/7\.0/.test(ia)||Da)&&Ja(Sa.prototype,"positionItem",function(a,b){var c=this,d=function(){b._legendItemPos&&
a.call(c,b)};d();setTimeout(d)});La.prototype={init:function(a,b){var c,d=a.series;a.series=null;c=D(I,a);c.series=a.series=d;this.userOptions=a;d=c.chart;this.margin=this.splashArray("margin",d);this.spacing=this.splashArray("spacing",d);var e=d.events;this.bounds={h:{},v:{}};this.callback=b;this.isResizing=0;this.options=c;this.axes=[];this.series=[];this.hasCartesianSeries=d.showAxes;var f=this,g;f.index=ba.length;ba.push(f);hb++;!1!==d.reflow&&L(f,"load",function(){f.initReflow()});if(e)for(g in e)L(f,
g,e[g]);f.xAxis=[];f.yAxis=[];f.animation=Y?!1:r(d.animation,!0);f.pointCount=f.colorCounter=f.symbolCounter=0;f.firstRender()},initSeries:function(a){var b=this.options.chart;(b=sa[a.type||b.type||b.defaultSeriesType])||S(17,!0);b=new b;b.init(this,a);return b},isInsidePlot:function(a,b,c){var d=c?b:a;a=c?a:b;return 0<=d&&d<=this.plotWidth&&0<=a&&a<=this.plotHeight},adjustTickAmounts:function(){!1!==this.options.chart.alignTicks&&s(this.axes,function(a){a.adjustTickAmount()});this.maxTicks=null},
redraw:function(a){var b=this.axes,c=this.series,d=this.pointer,e=this.legend,f=this.isDirtyLegend,g,h,k=this.hasCartesianSeries,l=this.isDirtyBox,m=c.length,p=m,q=this.renderer,n=q.isHidden(),t=[];R=r(a,this.animation);n&&this.cloneRenderTo();for(this.layOutTitles();p--;)if(a=c[p],a.options.stacking&&(g=!0,a.isDirty)){h=!0;break}if(h)for(p=m;p--;)a=c[p],a.options.stacking&&(a.isDirty=!0);s(c,function(a){a.isDirty&&"point"===a.options.legendType&&(f=!0)});f&&e.options.enabled&&(e.render(),this.isDirtyLegend=
!1);g&&this.getStacks();k&&(this.isResizing||(this.maxTicks=null,s(b,function(a){a.setScale()})),this.adjustTickAmounts());this.getMargins();k&&(s(b,function(a){a.isDirty&&(l=!0)}),s(b,function(a){a.isDirtyExtremes&&(a.isDirtyExtremes=!1,t.push(function(){M(a,"afterSetExtremes",y(a.eventArgs,a.getExtremes()));delete a.eventArgs}));(l||g)&&a.redraw()}));l&&this.drawChartBox();s(c,function(a){a.isDirty&&a.visible&&(!a.isCartesian||a.xAxis)&&a.redraw()});d&&d.reset(!0);q.draw();M(this,"redraw");n&&this.cloneRenderTo(!0);
s(t,function(a){a.call()})},get:function(a){var b=this.axes,c=this.series,d,e;for(d=0;d<b.length;d++)if(b[d].options.id===a)return b[d];for(d=0;d<c.length;d++)if(c[d].options.id===a)return c[d];for(d=0;d<c.length;d++)for(e=c[d].points||[],b=0;b<e.length;b++)if(e[b].id===a)return e[b];return null},getAxes:function(){var a=this,b=this.options,c=b.xAxis=oa(b.xAxis||{}),b=b.yAxis=oa(b.yAxis||{});s(c,function(a,b){a.index=b;a.isX=!0});s(b,function(a,b){a.index=b});c=c.concat(b);s(c,function(b){new Ba(a,
b)});a.adjustTickAmounts()},getSelectedPoints:function(){var a=[];s(this.series,function(b){a=a.concat(ib(b.points||[],function(a){return a.selected}))});return a},getSelectedSeries:function(){return ib(this.series,function(a){return a.selected})},getStacks:function(){var a=this;s(a.yAxis,function(a){a.stacks&&a.hasVisibleSeries&&(a.oldStacks=a.stacks)});s(a.series,function(b){!b.options.stacking||!0!==b.visible&&!1!==a.options.chart.ignoreHiddenSeries||(b.stackKey=b.type+r(b.options.stack,""))})},
setTitle:function(a,b,c){var d=this,e=d.options,f;f=e.title=D(e.title,a);e=e.subtitle=D(e.subtitle,b);s([["title",a,f],["subtitle",b,e]],function(a){var b=a[0],c=d[b],e=a[1];a=a[2];c&&e&&(d[b]=c=c.destroy());a&&a.text&&!c&&(d[b]=d.renderer.text(a.text,0,0,a.useHTML).attr({align:a.align,"class":"highcharts-"+b,zIndex:a.zIndex||4}).css(a.style).add())});d.layOutTitles(c)},layOutTitles:function(a){var b=0,c=this.title,d=this.subtitle,e=this.options,f=e.title,e=e.subtitle,g=this.renderer,h=this.spacingBox.width-
44;c&&(c.css({width:(f.width||h)+"px"}).align(y({y:g.fontMetrics(f.style.fontSize,c).b-3},f),!1,"spacingBox"),f.floating||f.verticalAlign||(b=c.getBBox().height));d&&(d.css({width:(e.width||h)+"px"}).align(y({y:b+(f.margin-13)+g.fontMetrics(f.style.fontSize,d).b},e),!1,"spacingBox"),e.floating||e.verticalAlign||(b=ka(b+d.getBBox().height)));c=this.titleOffset!==b;this.titleOffset=b;!this.isDirtyBox&&c&&(this.isDirtyBox=c,this.hasRendered&&r(a,!0)&&this.isDirtyBox&&this.redraw())},getChartSize:function(){var a=
this.options.chart,b=a.width,a=a.height,c=this.renderToClone||this.renderTo;u(b)||(this.containerWidth=Fa(c,"width"));u(a)||(this.containerHeight=Fa(c,"height"));this.chartWidth=v(0,b||this.containerWidth||600);this.chartHeight=v(0,r(a,19<this.containerHeight?this.containerHeight:400))},cloneRenderTo:function(a){var b=this.renderToClone,c=this.container;a?b&&(this.renderTo.appendChild(c),za(b),delete this.renderToClone):(c&&c.parentNode===this.renderTo&&this.renderTo.removeChild(c),this.renderToClone=
b=this.renderTo.cloneNode(0),N(b,{position:"absolute",top:"-9999px",display:"block"}),b.style.setProperty&&b.style.setProperty("display","block","important"),A.body.appendChild(b),c&&b.appendChild(c))},getContainer:function(){var a,b=this.options.chart,c,d,e;this.renderTo=a=b.renderTo;e="highcharts-"+Ma++;ea(a)&&(this.renderTo=a=A.getElementById(a));a||S(13,!0);c=B(C(a,"data-highcharts-chart"));!isNaN(c)&&ba[c]&&ba[c].hasRendered&&ba[c].destroy();C(a,"data-highcharts-chart",this.index);a.innerHTML=
"";b.skipClone||a.offsetWidth||this.cloneRenderTo();this.getChartSize();c=this.chartWidth;d=this.chartHeight;this.container=a=pa(Va,{className:"highcharts-container"+(b.className?" "+b.className:""),id:e},y({position:"relative",overflow:"hidden",width:c+"px",height:d+"px",textAlign:"left",lineHeight:"normal",zIndex:0,"-webkit-tap-highlight-color":"rgba(0,0,0,0)"},b.style),this.renderToClone||a);this._cursor=a.style.cursor;this.renderer=b.forExport?new ua(a,c,d,b.style,!0):new ua(a,c,d,b.style);Y&&
this.renderer.create(this,a,c,d)},getMargins:function(){var a=this.spacing,b,c=this.legend,d=this.margin,e=this.options.legend,f=r(e.margin,20),g=e.x,h=e.y,k=e.align,l=e.verticalAlign,m=this.titleOffset;this.resetMargins();b=this.axisOffset;m&&!u(d[0])&&(this.plotTop=v(this.plotTop,m+this.options.title.margin+a[0]));c.display&&!e.floating&&("right"===k?u(d[1])||(this.marginRight=v(this.marginRight,c.legendWidth-g+f+a[1])):"left"===k?u(d[3])||(this.plotLeft=v(this.plotLeft,c.legendWidth+g+f+a[3])):
"top"===l?u(d[0])||(this.plotTop=v(this.plotTop,c.legendHeight+h+f+a[0])):"bottom"!==l||u(d[2])||(this.marginBottom=v(this.marginBottom,c.legendHeight-h+f+a[2])));this.extraBottomMargin&&(this.marginBottom+=this.extraBottomMargin);this.extraTopMargin&&(this.plotTop+=this.extraTopMargin);this.hasCartesianSeries&&s(this.axes,function(a){a.getOffset()});u(d[3])||(this.plotLeft+=b[3]);u(d[0])||(this.plotTop+=b[0]);u(d[2])||(this.marginBottom+=b[2]);u(d[1])||(this.marginRight+=b[1]);this.setChartSize()},
reflow:function(a){var b=this,c=b.options.chart,d=b.renderTo,e=c.width||Fa(d,"width"),f=c.height||Fa(d,"height"),c=a?a.target:x,d=function(){b.container&&(b.setSize(e,f,!1),b.hasUserSize=null)};if(!b.hasUserSize&&e&&f&&(c===x||c===A)){if(e!==b.containerWidth||f!==b.containerHeight)clearTimeout(b.reflowTimeout),a?b.reflowTimeout=setTimeout(d,100):d();b.containerWidth=e;b.containerHeight=f}},initReflow:function(){var a=this,b=function(b){a.reflow(b)};L(x,"resize",b);L(a,"destroy",function(){T(x,"resize",
b)})},setSize:function(a,b,c){var d=this,e,f,g;d.isResizing+=1;g=function(){d&&M(d,"endResize",null,function(){d.isResizing-=1})};R=r(c,d.animation);d.oldChartHeight=d.chartHeight;d.oldChartWidth=d.chartWidth;u(a)&&(d.chartWidth=e=v(0,z(a)),d.hasUserSize=!!e);u(b)&&(d.chartHeight=f=v(0,z(b)));(R?kb:N)(d.container,{width:e+"px",height:f+"px"},R);d.setChartSize(!0);d.renderer.setSize(e,f,c);d.maxTicks=null;s(d.axes,function(a){a.isDirty=!0;a.setScale()});s(d.series,function(a){a.isDirty=!0});d.isDirtyLegend=
!0;d.isDirtyBox=!0;d.layOutTitles();d.getMargins();d.redraw(c);d.oldChartHeight=null;M(d,"resize");!1===R?g():setTimeout(g,R&&R.duration||500)},setChartSize:function(a){var b=this.inverted,c=this.renderer,d=this.chartWidth,e=this.chartHeight,f=this.options.chart,g=this.spacing,h=this.clipOffset,k,l,m,p;this.plotLeft=k=z(this.plotLeft);this.plotTop=l=z(this.plotTop);this.plotWidth=m=v(0,z(d-k-this.marginRight));this.plotHeight=p=v(0,z(e-l-this.marginBottom));this.plotSizeX=b?p:m;this.plotSizeY=b?m:
p;this.plotBorderWidth=f.plotBorderWidth||0;this.spacingBox=c.spacingBox={x:g[3],y:g[0],width:d-g[3]-g[1],height:e-g[0]-g[2]};this.plotBox=c.plotBox={x:k,y:l,width:m,height:p};d=2*Q(this.plotBorderWidth/2);b=ka(v(d,h[3])/2);c=ka(v(d,h[0])/2);this.clipBox={x:b,y:c,width:Q(this.plotSizeX-v(d,h[1])/2-b),height:v(0,Q(this.plotSizeY-v(d,h[2])/2-c))};a||s(this.axes,function(a){a.setAxisSize();a.setAxisTranslation()})},resetMargins:function(){var a=this.spacing,b=this.margin;this.plotTop=r(b[0],a[0]);this.marginRight=
r(b[1],a[1]);this.marginBottom=r(b[2],a[2]);this.plotLeft=r(b[3],a[3]);this.axisOffset=[0,0,0,0];this.clipOffset=[0,0,0,0]},drawChartBox:function(){var a=this.options.chart,b=this.renderer,c=this.chartWidth,d=this.chartHeight,e=this.chartBackground,f=this.plotBackground,g=this.plotBorder,h=this.plotBGImage,k=a.borderWidth||0,l=a.backgroundColor,m=a.plotBackgroundColor,p=a.plotBackgroundImage,q=a.plotBorderWidth||0,n,r=this.plotLeft,s=this.plotTop,u=this.plotWidth,w=this.plotHeight,v=this.plotBox,
x=this.clipRect,y=this.clipBox;n=k+(a.shadow?8:0);if(k||l)e?e.animate(e.crisp({width:c-n,height:d-n})):(e={fill:l||P},k&&(e.stroke=a.borderColor,e["stroke-width"]=k),this.chartBackground=b.rect(n/2,n/2,c-n,d-n,a.borderRadius,k).attr(e).addClass("highcharts-background").add().shadow(a.shadow));m&&(f?f.animate(v):this.plotBackground=b.rect(r,s,u,w,0).attr({fill:m}).add().shadow(a.plotShadow));p&&(h?h.animate(v):this.plotBGImage=b.image(p,r,s,u,w).add());x?x.animate({width:y.width,height:y.height}):
this.clipRect=b.clipRect(y);q&&(g?g.animate(g.crisp({x:r,y:s,width:u,height:w})):this.plotBorder=b.rect(r,s,u,w,0,-q).attr({stroke:a.plotBorderColor,"stroke-width":q,fill:P,zIndex:1}).add());this.isDirtyBox=!1},propFromSeries:function(){var a=this,b=a.options.chart,c,d=a.options.series,e,f;s(["inverted","angular","polar"],function(g){c=sa[b.type||b.defaultSeriesType];f=a[g]||b[g]||c&&c.prototype[g];for(e=d&&d.length;!f&&e--;)(c=sa[d[e].type])&&c.prototype[g]&&(f=!0);a[g]=f})},linkSeries:function(){var a=
this,b=a.series;s(b,function(a){a.linkedSeries.length=0});s(b,function(b){var d=b.options.linkedTo;ea(d)&&(d=":previous"===d?a.series[b.index-1]:a.get(d))&&(d.linkedSeries.push(b),b.linkedParent=d)})},renderSeries:function(){s(this.series,function(a){a.translate();a.setTooltipPoints&&a.setTooltipPoints();a.render()})},renderLabels:function(){var a=this,b=a.options.labels;b.items&&s(b.items,function(c){var d=y(b.style,c.style),e=B(d.left)+a.plotLeft,f=B(d.top)+a.plotTop+12;delete d.left;delete d.top;
a.renderer.text(c.html,e,f).attr({zIndex:2}).css(d).add()})},render:function(){var a=this.axes,b=this.renderer,c=this.options;this.setTitle();this.legend=new Sa(this,c.legend);this.getStacks();s(a,function(a){a.setScale()});this.getMargins();this.maxTicks=null;s(a,function(a){a.setTickPositions(!0);a.setMaxTicks()});this.adjustTickAmounts();this.getMargins();this.drawChartBox();this.hasCartesianSeries&&s(a,function(a){a.render()});this.seriesGroup||(this.seriesGroup=b.g("series-group").attr({zIndex:3}).add());
this.renderSeries();this.renderLabels();this.showCredits(c.credits);this.hasRendered=!0},showCredits:function(a){a.enabled&&!this.credits&&(this.credits=this.renderer.text(a.text,0,0).on("click",function(){a.href&&(location.href=a.href)}).attr({align:a.position.align,zIndex:8}).css(a.style).add().align(a.position))},destroy:function(){var a=this,b=a.axes,c=a.series,d=a.container,e,f=d&&d.parentNode;M(a,"destroy");ba[a.index]=w;hb--;a.renderTo.removeAttribute("data-highcharts-chart");T(a);for(e=b.length;e--;)b[e]=
b[e].destroy();for(e=c.length;e--;)c[e]=c[e].destroy();s("title subtitle chartBackground plotBackground plotBGImage plotBorder seriesGroup clipRect credits pointer scroller rangeSelector legend resetZoomButton tooltip renderer".split(" "),function(b){var c=a[b];c&&c.destroy&&(a[b]=c.destroy())});d&&(d.innerHTML="",T(d),f&&za(d));for(e in a)delete a[e]},isReadyToRender:function(){var a=this;return!O&&x==x.top&&"complete"!==A.readyState||Y&&!x.canvg?(Y?CanVGController.push(function(){a.firstRender()},
a.options.global.canvasToolsURL):A.attachEvent("onreadystatechange",function(){A.detachEvent("onreadystatechange",a.firstRender);"complete"===A.readyState&&a.firstRender()}),!1):!0},firstRender:function(){var a=this,b=a.options,c=a.callback;a.isReadyToRender()&&(a.getContainer(),M(a,"init"),a.resetMargins(),a.setChartSize(),a.propFromSeries(),a.getAxes(),s(b.series||[],function(b){a.initSeries(b)}),a.linkSeries(),M(a,"beforeRender"),ca.Pointer&&(a.pointer=new Pointer(a,b)),a.render(),a.renderer.draw(),
c&&c.apply(a,[a]),s(a.callbacks,function(b){b.apply(a,[a])}),a.cloneRenderTo(!0),M(a,"load"))},splashArray:function(a,b){var c=b[a],c=Z(c)?c:[c,c,c,c];return[r(b[a+"Top"],c[0]),r(b[a+"Right"],c[1]),r(b[a+"Bottom"],c[2]),r(b[a+"Left"],c[3])]}};La.prototype.callbacks=[];var Ha=function(){};Ha.prototype={init:function(a,b,c){this.series=a;this.applyOptions(b,c);this.pointAttr={};a.options.colorByPoint&&(b=a.options.colors||a.chart.options.colors,this.color=this.color||b[a.colorCounter++],a.colorCounter===
b.length&&(a.colorCounter=0));a.chart.pointCount++;return this},applyOptions:function(a,b){var c=this.series,d=c.options.pointValKey||c.pointValKey;a=Ha.prototype.optionsToObject.call(this,a);y(this,a);this.options=this.options?y(this.options,a):a;d&&(this.y=this[d]);this.x===w&&c&&(this.x=b===w?c.autoIncrement():b);return this},optionsToObject:function(a){var b={},c=this.series,d=c.pointArrayMap||["y"],e=d.length,f=0,g=0;if("number"===typeof a||null===a)b[d[0]]=a;else if(ma(a))for(a.length>e&&(c=
typeof a[0],"string"===c?b.name=a[0]:"number"===c&&(b.x=a[0]),f++);g<e;)b[d[g++]]=a[f++];else"object"===typeof a&&(b=a,a.dataLabels&&(c._hasPointLabels=!0),a.marker&&(c._hasPointMarkers=!0));return b},destroy:function(){var a=this.series.chart,b=a.hoverPoints,c;a.pointCount--;b&&(this.setState(),na(b,this),b.length||(a.hoverPoints=null));if(this===a.hoverPoint)this.onMouseOut();if(this.graphic||this.dataLabel)T(this),this.destroyElements();this.legendItem&&a.legend.destroyItem(this);for(c in this)this[c]=
null},destroyElements:function(){for(var a="graphic dataLabel dataLabelUpper group connector shadowGroup".split(" "),b,c=6;c--;)b=a[c],this[b]&&(this[b]=this[b].destroy())},getLabelConfig:function(){return{x:this.category,y:this.y,key:this.name||this.category,series:this.series,point:this,percentage:this.percentage,total:this.total||this.stackTotal}},tooltipFormatter:function(a){var b=this.series,c=b.tooltipOptions,d=r(c.valueDecimals,""),e=c.valuePrefix||"",f=c.valueSuffix||"";s(b.pointArrayMap||
["y"],function(b){b="{point."+b;if(e||f)a=a.replace(b+"}",e+b+"}"+f);a=a.replace(b+"}",b+":,."+d+"f}")});return va(a,{point:this,series:this.series})},firePointEvent:function(a,b,c){var d=this,e=this.series.options;(e.point.events[a]||d.options&&d.options.events&&d.options.events[a])&&this.importEvents();"click"===a&&e.allowPointSelect&&(c=function(a){d.select(null,a.ctrlKey||a.metaKey||a.shiftKey)});M(this,a,b,c)}};var Ta=function(){};Ta.prototype={isCartesian:!0,type:"line",pointClass:Ha,sorted:!0,
requireSorting:!0,pointAttrToOptions:{stroke:"lineColor","stroke-width":"lineWidth",fill:"fillColor",r:"radius"},axisTypes:["xAxis","yAxis"],colorCounter:0,parallelArrays:["x","y"],init:function(a,b){var c=this,d,e,f=a.series,g=function(a,b){return r(a.options.index,a._i)-r(b.options.index,b._i)};c.chart=a;c.options=b=c.setOptions(b);c.linkedSeries=[];c.bindAxes();y(c,{name:b.name,state:"",pointAttr:{},visible:!1!==b.visible,selected:!0===b.selected});Y&&(b.animation=!1);e=b.events;for(d in e)L(c,
d,e[d]);if(e&&e.click||b.point&&b.point.events&&b.point.events.click||b.allowPointSelect)a.runTrackerClick=!0;c.getColor();c.getSymbol();s(c.parallelArrays,function(a){c[a+"Data"]=[]});c.setData(b.data,!1);c.isCartesian&&(a.hasCartesianSeries=!0);f.push(c);c._i=f.length-1;Ka(f,g);this.yAxis&&Ka(this.yAxis.series,g);s(f,function(a,b){a.index=b;a.name=a.name||"Series "+(b+1)})},bindAxes:function(){var a=this,b=a.options,c=a.chart,d;s(a.axisTypes||[],function(e){s(c[e],function(c){d=c.options;if(b[e]===
d.index||b[e]!==w&&b[e]===d.id||b[e]===w&&0===d.index)c.series.push(a),a[e]=c,c.isDirty=!0});a[e]||a.optionalAxis===e||S(18,!0)})},updateParallelArrays:function(a,b){var c=a.series,d=arguments;s(c.parallelArrays,"number"===typeof b?function(d){var f="y"===d&&c.toYData?c.toYData(a):a[d];c[d+"Data"][b]=f}:function(a){Array.prototype[b].apply(c[a+"Data"],Array.prototype.slice.call(d,2))})},autoIncrement:function(){var a=this.options,b=this.xIncrement,b=r(b,a.pointStart,0);this.pointInterval=r(this.pointInterval,
a.pointInterval,1);this.xIncrement=b+this.pointInterval;return b},getSegments:function(){var a=-1,b=[],c,d=this.points,e=d.length;if(e)if(this.options.connectNulls){for(c=e;c--;)null===d[c].y&&d.splice(c,1);d.length&&(b=[d])}else s(d,function(c,g){null===c.y?(g>a+1&&b.push(d.slice(a+1,g)),a=g):g===e-1&&b.push(d.slice(a+1,g+1))});this.segments=b},setOptions:function(a){var b=this.chart,c=b.options.plotOptions,b=b.userOptions||{},d=b.plotOptions||{},e=c[this.type];this.userOptions=a;c=D(e,c.series,
a);this.tooltipOptions=D(I.tooltip,I.plotOptions[this.type].tooltip,b.tooltip,d.series&&d.series.tooltip,d[this.type]&&d[this.type].tooltip,a.tooltip);null===e.marker&&delete c.marker;return c},getCyclic:function(a,b,c){var d=this.userOptions,e="_"+a+"Index",f=a+"Counter";b||(u(d[e])?b=d[e]:(d[e]=b=this.chart[f]%c.length,this.chart[f]+=1),b=c[b]);this[a]=b},getColor:function(){this.options.colorByPoint||this.getCyclic("color",this.options.color||Qa[this.type].color,this.chart.options.colors)},getSymbol:function(){var a=
this.options.marker;this.getCyclic("symbol",a.symbol,this.chart.options.symbols);/^url/.test(this.symbol)&&(a.radius=0)},drawLegendSymbol:vb.drawLineMarker,setData:function(a,b,c,d){var e=this,f=e.points,g=f&&f.length||0,h,k=e.options,l=e.chart,m=null,p=e.xAxis,q=p&&!!p.categories,n=e.tooltipPoints,t=k.turboThreshold,u=this.xData,v=this.yData,x=(h=e.pointArrayMap)&&h.length;a=a||[];h=a.length;b=r(b,!0);if(!1===d||!h||g!==h||e.cropped||e.hasGroupedData){e.xIncrement=null;e.pointRange=q?1:k.pointRange;
e.colorCounter=0;s(this.parallelArrays,function(a){e[a+"Data"].length=0});if(t&&h>t){for(c=0;null===m&&c<h;)m=a[c],c++;if($(m)){q=r(k.pointStart,0);k=r(k.pointInterval,1);for(c=0;c<h;c++)u[c]=q,v[c]=a[c],q+=k;e.xIncrement=q}else if(ma(m))if(x)for(c=0;c<h;c++)k=a[c],u[c]=k[0],v[c]=k.slice(1,x+1);else for(c=0;c<h;c++)k=a[c],u[c]=k[0],v[c]=k[1];else S(12)}else for(c=0;c<h;c++)a[c]!==w&&(k={series:e},e.pointClass.prototype.applyOptions.apply(k,[a[c]]),e.updateParallelArrays(k,c),q&&k.name&&(p.names[k.x]=
k.name));ea(v[0])&&S(14,!0);e.data=[];e.options.data=a;for(c=g;c--;)f[c]&&f[c].destroy&&f[c].destroy();n&&(n.length=0);p&&(p.minRange=p.userMinRange);e.isDirty=e.isDirtyData=l.isDirtyBox=!0;c=!1}else s(a,function(a,b){f[b].update(a,!1)});b&&l.redraw(c)},processData:function(a){var b=this.xData,c=this.yData,d=b.length,e;e=0;var f,g,h=this.xAxis,k=this.options,l=k.cropThreshold,m=0,p=this.isCartesian,q,n;if(p&&!this.isDirty&&!h.isDirty&&!this.yAxis.isDirty&&!a)return!1;if(p&&this.sorted&&(!l||d>l||
this.forceCrop))if(q=h.getExtremes(),n=q.min,q=q.max,b[d-1]<n||b[0]>q)b=[],c=[];else if(b[0]<n||b[d-1]>q)e=this.cropData(this.xData,this.yData,n,q),b=e.xData,c=e.yData,e=e.start,f=!0,m=b.length;for(a=b.length-1;0<=a;a--)d=b[a]-b[a-1],!f&&b[a]>n&&b[a]<q&&m++,0<d&&(g===w||d<g)?g=d:0>d&&this.requireSorting&&S(15);this.cropped=f;this.cropStart=e;this.processedXData=b;this.processedYData=c;this.activePointCount=m;null===k.pointRange&&(this.pointRange=g||1);this.closestPointRange=g},cropData:function(a,
b,c,d){var e=a.length,f=0,g=e,h=r(this.cropShoulder,1),k;for(k=0;k<e;k++)if(a[k]>=c){f=v(0,k-h);break}for(;k<e;k++)if(a[k]>d){g=k+h;break}return{xData:a.slice(f,g),yData:b.slice(f,g),start:f,end:g}},generatePoints:function(){var a=this.options.data,b=this.data,c,d=this.processedXData,e=this.processedYData,f=this.pointClass,g=d.length,h=this.cropStart||0,k,l=this.hasGroupedData,m,p=[],q;b||l||(b=[],b.length=a.length,b=this.data=b);for(q=0;q<g;q++)k=h+q,l?p[q]=(new f).init(this,[d[q]].concat(oa(e[q]))):
(b[k]?m=b[k]:a[k]!==w&&(b[k]=m=(new f).init(this,a[k],d[q])),p[q]=m);if(b&&(g!==(c=b.length)||l))for(q=0;q<c;q++)q!==h||l||(q+=g),b[q]&&(b[q].destroyElements(),b[q].plotX=w);this.data=b;this.points=p},getExtremes:function(a){var b=this.yAxis,c=this.processedXData,d,e=[],f=0;d=this.xAxis.getExtremes();var g=d.min,h=d.max,k,l,m,p;a=a||this.stackedYData||this.processedYData;d=a.length;for(p=0;p<d;p++)if(l=c[p],m=a[p],k=null!==m&&m!==w&&(!b.isLog||m.length||0<m),l=this.getExtremesFromAll||this.cropped||
(c[p+1]||l)>=g&&(c[p-1]||l)<=h,k&&l)if(k=m.length)for(;k--;)null!==m[k]&&(e[f++]=m[k]);else e[f++]=m;this.dataMin=r(void 0,xa(e));this.dataMax=r(void 0,qa(e))},translate:function(){this.processedXData||this.processData();this.generatePoints();for(var a=this.options,b=a.stacking,c=this.xAxis,d=c.categories,e=this.yAxis,f=this.points,g=f.length,h=!!this.modifyValue,k=a.pointPlacement,l="between"===k||$(k),m=a.threshold,a=0;a<g;a++){var p=f[a],q=p.x,n=p.y,t=p.low,s=b&&e.stacks[(this.negStacks&&n<m?"-":
"")+this.stackKey];e.isLog&&0>=n&&(p.y=n=null);p.plotX=c.translate(q,0,0,0,1,k,"flags"===this.type);b&&this.visible&&s&&s[q]&&(s=s[q],n=s.points[this.index+","+a],t=n[0],n=n[1],0===t&&(t=r(m,e.min)),e.isLog&&0>=t&&(t=null),p.total=p.stackTotal=s.total,p.percentage=s.total&&p.y/s.total*100,p.stackY=n,s.setOffset(this.pointXOffset||0,this.barW||0));p.yBottom=u(t)?e.translate(t,0,1,0,1):null;h&&(n=this.modifyValue(n,p));p.plotY="number"===typeof n&&Infinity!==n?e.translate(n,0,1,0,1):w;p.clientX=l?c.translate(q,
0,0,0,1):p.plotX;p.negative=p.y<(m||0);p.category=d&&d[p.x]!==w?d[p.x]:p.x}this.getSegments()},animate:function(a){var b=this.chart,c=b.renderer,d;d=this.options.animation;var e=this.clipBox||b.clipBox,f=b.inverted,g;d&&!Z(d)&&(d=Qa[this.type].animation);g=["_sharedClip",d.duration,d.easing,e.height].join();a?(a=b[g],d=b[g+"m"],a||(b[g]=a=c.clipRect(y(e,{width:0})),b[g+"m"]=d=c.clipRect(-99,f?-b.plotLeft:-b.plotTop,99,f?b.chartWidth:b.chartHeight)),this.group.clip(a),this.markerGroup.clip(d),this.sharedClipKey=
g):((a=b[g])&&a.animate({width:b.plotSizeX},d),b[g+"m"]&&b[g+"m"].animate({width:b.plotSizeX+99},d),this.animate=null)},afterAnimate:function(){var a=this.chart,b=this.sharedClipKey,c=this.group,d=this.clipBox;c&&!1!==this.options.clip&&(b&&d||c.clip(d?a.renderer.clipRect(d):a.clipRect),this.markerGroup.clip());M(this,"afterAnimate");setTimeout(function(){b&&a[b]&&(d||(a[b]=a[b].destroy()),a[b+"m"]&&(a[b+"m"]=a[b+"m"].destroy()))},100)},drawPoints:function(){var a,b=this.points,c=this.chart,d,e,f,
g,h,k,l,m;d=this.options.marker;var p=this.pointAttr[""],q,n=this.markerGroup,s=r(d.enabled,this.activePointCount<.5*this.xAxis.len/d.radius);if(!1!==d.enabled||this._hasPointMarkers)for(f=b.length;f--;)g=b[f],d=Q(g.plotX),e=g.plotY,m=g.graphic,k=g.marker||{},a=s&&k.enabled===w||k.enabled,q=c.isInsidePlot(z(d),e,c.inverted),a&&e!==w&&!isNaN(e)&&null!==g.y?(a=g.pointAttr[g.selected?"select":""]||p,h=a.r,k=r(k.symbol,this.symbol),l=0===k.indexOf("url"),m?m[q?"show":"hide"](!0).animate(y({x:d-h,y:e-
h},m.symbolName?{width:2*h,height:2*h}:{})):q&&(0<h||l)&&(g.graphic=c.renderer.symbol(k,d-h,e-h,2*h,2*h).attr(a).add(n))):m&&(g.graphic=m.destroy())},convertAttribs:function(a,b,c,d){var e=this.pointAttrToOptions,f,g,h={};a=a||{};b=b||{};c=c||{};d=d||{};for(f in e)g=e[f],h[f]=r(a[g],b[f],c[f],d[f]);return h},getAttribs:function(){var a=this,b=a.options,c=Qa[a.type].marker?b.marker:b,d=c.states,e=d.hover,f,g=a.color;f={stroke:g,fill:g};var h=a.points||[],k,l=[],m,p=a.pointAttrToOptions;m=a.hasPointSpecificOptions;
var q=b.negativeColor,n=c.lineColor,r=c.fillColor;k=b.turboThreshold;var v;b.marker?(e.radius=e.radius||c.radius+e.radiusPlus,e.lineWidth=e.lineWidth||c.lineWidth+e.lineWidthPlus):e.color=e.color||ta(e.color||g).brighten(e.brightness).get();l[""]=a.convertAttribs(c,f);s(["hover","select"],function(b){l[b]=a.convertAttribs(d[b],l[""])});a.pointAttr=l;g=h.length;if(!k||g<k||m)for(;g--;){k=h[g];(c=k.options&&k.options.marker||k.options)&&!1===c.enabled&&(c.radius=0);k.negative&&q&&(k.color=k.fillColor=
q);m=b.colorByPoint||k.color;if(k.options)for(v in p)u(c[p[v]])&&(m=!0);m?(c=c||{},m=[],d=c.states||{},f=d.hover=d.hover||{},b.marker||(f.color=f.color||!k.options.color&&e.color||ta(k.color).brighten(f.brightness||e.brightness).get()),f={color:k.color},r||(f.fillColor=k.color),n||(f.lineColor=k.color),m[""]=a.convertAttribs(y(f,c),l[""]),m.hover=a.convertAttribs(d.hover,l.hover,m[""]),m.select=a.convertAttribs(d.select,l.select,m[""])):m=l;k.pointAttr=m}},destroy:function(){var a=this,b=a.chart,
c=/AppleWebKit\/533/.test(ia),d,e,f=a.data||[],g,h,k;M(a,"destroy");T(a);s(a.axisTypes||[],function(b){if(k=a[b])na(k.series,a),k.isDirty=k.forceRedraw=!0});a.legendItem&&a.chart.legend.destroyItem(a);for(e=f.length;e--;)(g=f[e])&&g.destroy&&g.destroy();a.points=null;clearTimeout(a.animationTimeout);s("area graph dataLabelsGroup group markerGroup tracker graphNeg areaNeg posClip negClip".split(" "),function(b){a[b]&&(d=c&&"group"===b?"hide":"destroy",a[b][d]())});b.hoverSeries===a&&(b.hoverSeries=
null);na(b.series,a);for(h in a)delete a[h]},getSegmentPath:function(a){var b=this,c=[],d=b.options.step;s(a,function(e,f){var g=e.plotX,h=e.plotY,k;b.getPointSpline?c.push.apply(c,b.getPointSpline(a,e,f)):(c.push(f?"L":"M"),d&&f&&(k=a[f-1],"right"===d?c.push(k.plotX,h):"center"===d?c.push((k.plotX+g)/2,k.plotY,(k.plotX+g)/2,h):c.push(g,k.plotY)),c.push(e.plotX,e.plotY))});return c},getGraphPath:function(){var a=this,b=[],c,d=[];s(a.segments,function(e){c=a.getSegmentPath(e);1<e.length?b=b.concat(c):
d.push(e[0])});a.singlePoints=d;return a.graphPath=b},drawGraph:function(){var a=this,b=this.options,c=[["graph",b.lineColor||this.color]],d=b.lineWidth,e=b.dashStyle,f="square"!==b.linecap,g=this.getGraphPath(),h=b.negativeColor;h&&c.push(["graphNeg",h]);s(c,function(c,h){var m=c[0],p=a[m];p?(Oa(p),p.animate({d:g})):d&&g.length&&(p={stroke:c[1],"stroke-width":d,fill:P,zIndex:1},e?p.dashstyle=e:f&&(p["stroke-linecap"]=p["stroke-linejoin"]="round"),a[m]=a.chart.renderer.path(g).attr(p).add(a.group).shadow(!h&&
b.shadow))})},clipNeg:function(){var a=this.options,b=this.chart,c=b.renderer,d=a.negativeColor||a.negativeFillColor,e,f=this.graph,g=this.area,h=this.posClip,k=this.negClip;e=b.chartWidth;var l=b.chartHeight,m=v(e,l),p=this.yAxis;d&&(f||g)&&(d=z(p.toPixels(a.threshold||0,!0)),0>d&&(m-=d),a={x:0,y:0,width:m,height:d},m={x:0,y:d,width:m,height:m},b.inverted&&(a.height=m.y=b.plotWidth-d,c.isVML&&(a={x:b.plotWidth-d-b.plotLeft,y:0,width:e,height:l},m={x:d+b.plotLeft-e,y:0,width:b.plotLeft+d,height:e})),
p.reversed?(b=m,e=a):(b=a,e=m),h?(h.animate(b),k.animate(e)):(this.posClip=h=c.clipRect(b),this.negClip=k=c.clipRect(e),f&&this.graphNeg&&(f.clip(h),this.graphNeg.clip(k)),g&&(g.clip(h),this.areaNeg.clip(k))))},invertGroups:function(){function a(){var a={width:b.yAxis.len,height:b.xAxis.len};s(["group","markerGroup"],function(c){b[c]&&b[c].attr(a).invert()})}var b=this,c=b.chart;b.xAxis&&(L(c,"resize",a),L(b,"destroy",function(){T(c,"resize",a)}),a(),b.invertGroups=a)},plotGroup:function(a,b,c,d,
e){var f=this[a],g=!f;g&&(this[a]=f=this.chart.renderer.g(b).attr({visibility:c,zIndex:d||.1}).add(e));f[g?"attr":"animate"](this.getPlotBox());return f},getPlotBox:function(){var a=this.chart,b=this.xAxis,c=this.yAxis;a.inverted&&(b=c,c=this.xAxis);return{translateX:b?b.left:a.plotLeft,translateY:c?c.top:a.plotTop,scaleX:1,scaleY:1}},render:function(){var a=this,b=a.chart,c,d=a.options,e=(c=d.animation)&&!!a.animate&&b.renderer.isSVG&&r(c.duration,500)||0,f=a.visible?"visible":"hidden",g=d.zIndex,
h=a.hasRendered,k=b.seriesGroup;c=a.plotGroup("group","series",f,g,k);a.markerGroup=a.plotGroup("markerGroup","markers",f,g,k);e&&a.animate(!0);a.getAttribs();c.inverted=a.isCartesian?b.inverted:!1;a.drawGraph&&(a.drawGraph(),a.clipNeg());a.drawDataLabels&&a.drawDataLabels();a.visible&&a.drawPoints();a.drawTracker&&!1!==a.options.enableMouseTracking&&a.drawTracker();b.inverted&&a.invertGroups();!1===d.clip||a.sharedClipKey||h||c.clip(b.clipRect);e&&a.animate();h||(e?a.animationTimeout=setTimeout(function(){a.afterAnimate()},
e):a.afterAnimate());a.isDirty=a.isDirtyData=!1;a.hasRendered=!0},redraw:function(){var a=this.chart,b=this.isDirtyData,c=this.group,d=this.xAxis,e=this.yAxis;c&&(a.inverted&&c.attr({width:a.plotWidth,height:a.plotHeight}),c.animate({translateX:r(d&&d.left,a.plotLeft),translateY:r(e&&e.top,a.plotTop)}));this.translate();this.setTooltipPoints&&this.setTooltipPoints(!0);this.render();b&&M(this,"updatedData")}};var wb=Ua(Ta);sa.line=wb;y(ca,{Axis:Ba,Chart:La,Color:ta,Point:Ha,Tick:ja,Renderer:ua,Series:Ta,
SVGElement:K,SVGRenderer:ua,arrayMin:xa,arrayMax:qa,charts:ba,dateFormat:wa,format:va,pathAnim:Na,getOptions:function(){return I},hasBidiBug:pb,isTouchDevice:fb,numberFormat:ga,seriesTypes:sa,setOptions:function(a){I=D(!0,I,a);Wa();return I},addEvent:L,removeEvent:T,createElement:pa,discardElement:za,css:N,each:s,extend:y,map:jb,merge:D,pick:r,splat:oa,extendClass:Ua,pInt:B,wrap:Ja,svg:O,canvas:Y,vml:!O&&!Y,product:"Highcharts 4.0.3",version:"/Highstock 2.0.3"})})(); 
